WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
@@pqa_service_pkg.pks
SHOW ERRORS PACKAGE PQA_SERVICE_PKG
@@pqa_service_pkg.pkb
SHOW ERRORS PACKAGE BODY PQA_SERVICE_PKG
PROMPT PQA_SERVICE_PKG installed successfully.
