WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
PROMPT Installing PRD_REPOSITORY_PKG...
@@prd_repository_pkg.pks
SHOW ERRORS PACKAGE PRD_REPOSITORY_PKG
@@prd_repository_pkg.pkb
SHOW ERRORS PACKAGE BODY PRD_REPOSITORY_PKG
DECLARE
  l_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO l_count FROM USER_ERRORS
   WHERE NAME='PRD_REPOSITORY_PKG' AND TYPE IN ('PACKAGE','PACKAGE BODY');
  IF l_count>0 THEN
    RAISE_APPLICATION_ERROR(-20999,'PRD_REPOSITORY_PKG possui erros.');
  END IF;
END;
/
PROMPT PRD_REPOSITORY_PKG installed successfully.
