WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
@@pim_service_pkg.pks
SHOW ERRORS PACKAGE PIM_SERVICE_PKG
@@pim_service_pkg.pkb
SHOW ERRORS PACKAGE BODY PIM_SERVICE_PKG
PROMPT PIM_SERVICE_PKG installed successfully.
