WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
PROMPT Installing PRD_SERVICE_PKG...
@@prd_service_pkg.pks
SHOW ERRORS PACKAGE PRD_SERVICE_PKG
@@prd_service_pkg.pkb
SHOW ERRORS PACKAGE BODY PRD_SERVICE_PKG
DECLARE
  l_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO l_count FROM USER_ERRORS
   WHERE NAME='PRD_SERVICE_PKG' AND TYPE IN ('PACKAGE','PACKAGE BODY');
  IF l_count>0 THEN
    RAISE_APPLICATION_ERROR(-20999,'PRD_SERVICE_PKG possui erros.');
  END IF;
END;
/
PROMPT PRD_SERVICE_PKG installed successfully.
