WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
@@pim_repository_pkg.pks
SHOW ERRORS PACKAGE PIM_REPOSITORY_PKG
@@pim_repository_pkg.pkb
SHOW ERRORS PACKAGE BODY PIM_REPOSITORY_PKG
PROMPT PIM_REPOSITORY_PKG installed successfully.
