WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
PROMPT Installing PRD_API_PKG...
@@prd_api_pkg.pks
SHOW ERRORS PACKAGE PRD_API_PKG
@@prd_api_pkg.pkb
SHOW ERRORS PACKAGE BODY PRD_API_PKG
DECLARE
  l_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO l_count FROM USER_ERRORS
   WHERE NAME='PRD_API_PKG' AND TYPE IN ('PACKAGE','PACKAGE BODY');
  IF l_count>0 THEN RAISE_APPLICATION_ERROR(-20999,'PRD_API_PKG possui erros.'); END IF;
END;
/
PROMPT PRD_API_PKG installed successfully.
