WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
@@pqa_repository_pkg.pks
SHOW ERRORS PACKAGE PQA_REPOSITORY_PKG
@@pqa_repository_pkg.pkb
SHOW ERRORS PACKAGE BODY PQA_REPOSITORY_PKG
PROMPT PQA_REPOSITORY_PKG installed successfully.
