WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
PROMPT Installing BRD_REPOSITORY_PKG...
@@brd_repository_pkg.pks
SHOW ERRORS PACKAGE BRD_REPOSITORY_PKG
@@brd_repository_pkg.pkb
SHOW ERRORS PACKAGE BODY BRD_REPOSITORY_PKG
DECLARE l_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO l_count FROM USER_ERRORS
   WHERE NAME='BRD_REPOSITORY_PKG';
  IF l_count>0 THEN RAISE_APPLICATION_ERROR(-20999,'BRD_REPOSITORY_PKG possui erros.'); END IF;
END;
/
PROMPT BRD_REPOSITORY_PKG installed successfully.
