WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
@@pqa_rule_pkg.pks
SHOW ERRORS PACKAGE PQA_RULE_PKG
@@pqa_rule_pkg.pkb
SHOW ERRORS PACKAGE BODY PQA_RULE_PKG
PROMPT PQA_RULE_PKG installed successfully.
