WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
@@pim_rule_pkg.pks
SHOW ERRORS PACKAGE PIM_RULE_PKG
@@pim_rule_pkg.pkb
SHOW ERRORS PACKAGE BODY PIM_RULE_PKG
PROMPT PIM_RULE_PKG installed successfully.
