SET SERVEROUTPUT ON SIZE UNLIMITED
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

@@pfl_api_pkg.pks
SHOW ERRORS PACKAGE PFL_API_PKG
@@pfl_api_pkg.pkb
SHOW ERRORS PACKAGE BODY PFL_API_PKG

DECLARE
  l_valid PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO l_valid
    FROM USER_OBJECTS
   WHERE OBJECT_NAME = 'PFL_API_PKG'
     AND OBJECT_TYPE IN ('PACKAGE', 'PACKAGE BODY')
     AND STATUS = 'VALID';
  IF l_valid <> 2 THEN
    RAISE_APPLICATION_ERROR(-20999, 'PFL_API_PKG nao esta valido.');
  END IF;
  DBMS_OUTPUT.PUT_LINE('SUCCESS - PFL_API_PKG VALID');
END;
/
