CREATE OR REPLACE PACKAGE BODY stp_query_pkg AS
  FUNCTION get_plan(p_code VARCHAR2)RETURN t_record IS r t_record;BEGIN BEGIN SELECT STP_PUBLIC_ID,STP_CODE,STP_NAME,
    STP_DESCRIPTION,STP_PRICE,STP_STATUS INTO r FROM BEX_STORE_PLAN WHERE STP_CODE=UPPER(TRIM(p_code));
    EXCEPTION WHEN NO_DATA_FOUND THEN RAISE e_not_found;END;RETURN r;END;
  FUNCTION list_active RETURN t_records IS x t_records;n PLS_INTEGER:=0;BEGIN FOR q IN(
    SELECT STP_CODE FROM BEX_STORE_PLAN WHERE STP_STATUS='ACTIVE' ORDER BY NVL(STP_PRICE,999999),STP_CODE)LOOP n:=n+1;x(n):=get_plan(q.STP_CODE);END LOOP;RETURN x;END;
END stp_query_pkg;
/
