WHENEVER SQLERROR EXIT SQL.SQLCODE;

DECLARE
    l_object_count  PLS_INTEGER;
    l_account_count PLS_INTEGER;
    l_store_count   PLS_INTEGER;
BEGIN
    SELECT COUNT(*) INTO l_object_count
      FROM USER_OBJECTS
     WHERE OBJECT_NAME = 'BEX_STORE_USER';

    IF l_object_count > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20000,
            'BEX_STORE_USER already exists or conflicts with an existing object'
        );
    END IF;

    SELECT COUNT(*) INTO l_account_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'BEX_ACCOUNT';

    SELECT COUNT(*) INTO l_store_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'BEX_STORE';

    IF l_account_count <> 1 THEN
        RAISE_APPLICATION_ERROR(-20001, 'BEX_ACCOUNT must exist before BEX_STORE_USER is created');
    END IF;

    IF l_store_count <> 1 THEN
        RAISE_APPLICATION_ERROR(-20002, 'BEX_STORE must exist before BEX_STORE_USER is created');
    END IF;
END;
/

CREATE TABLE BEX_STORE_USER
(
    STU_ID          NUMBER(19)
                    GENERATED BY DEFAULT AS IDENTITY
                    (
                        START WITH 1
                        INCREMENT BY 1
                        CACHE 20
                        NOCYCLE
                    ) NOT NULL,
    STU_PUBLIC_ID   CHAR(32 CHAR) NOT NULL,
    STR_ID          NUMBER(19) NOT NULL,
    ACC_ID          NUMBER(19) NOT NULL,
    STU_ROLE_CODE   VARCHAR2(50 CHAR) NOT NULL,
    STU_STATUS      VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    STU_JOINED_AT   TIMESTAMP(6) NOT NULL,
    STU_LEFT_AT     TIMESTAMP(6),
    STU_CREATED_AT  TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    STU_UPDATED_AT  TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    STU_CREATED_BY  NUMBER(19),
    STU_UPDATED_BY  NUMBER(19),
    CONSTRAINT PK_STORE_USER PRIMARY KEY (STU_ID),
    CONSTRAINT UK_STORE_USER_PUBLIC_ID UNIQUE (STU_PUBLIC_ID),
    CONSTRAINT FK_STU_STORE FOREIGN KEY (STR_ID)
        REFERENCES BEX_STORE (STR_ID),
    CONSTRAINT FK_STU_ACCOUNT FOREIGN KEY (ACC_ID)
        REFERENCES BEX_ACCOUNT (ACC_ID),
    CONSTRAINT FK_STU_CREATED_BY_ACCOUNT FOREIGN KEY (STU_CREATED_BY)
        REFERENCES BEX_ACCOUNT (ACC_ID),
    CONSTRAINT FK_STU_UPDATED_BY_ACCOUNT FOREIGN KEY (STU_UPDATED_BY)
        REFERENCES BEX_ACCOUNT (ACC_ID),
    CONSTRAINT CK_STU_ROLE_CODE CHECK
    (
        STU_ROLE_CODE IN ('ADMIN', 'MANAGER', 'ATTENDANT', 'COLLABORATOR')
    ),
    CONSTRAINT CK_STU_STATUS CHECK
    (
        STU_STATUS IN ('ACTIVE', 'INACTIVE')
    )
);

COMMENT ON TABLE BEX_STORE_USER IS
    'Operational participation of an account in a store with a store-specific role';
COMMENT ON COLUMN BEX_STORE_USER.STU_ID IS
    'Internal technical identifier generated by Oracle';
COMMENT ON COLUMN BEX_STORE_USER.STU_PUBLIC_ID IS
    'Immutable public identifier assigned by the application service';
COMMENT ON COLUMN BEX_STORE_USER.STR_ID IS
    'Internal identifier of the store in which the account participates';
COMMENT ON COLUMN BEX_STORE_USER.ACC_ID IS
    'Internal identifier of the operational account';
COMMENT ON COLUMN BEX_STORE_USER.STU_ROLE_CODE IS
    'Required store-specific operational role with no implicit default';
COMMENT ON COLUMN BEX_STORE_USER.STU_STATUS IS
    'Current lifecycle status of the operational participation';
COMMENT ON COLUMN BEX_STORE_USER.STU_JOINED_AT IS
    'Timestamp when the account joined the store operation';
COMMENT ON COLUMN BEX_STORE_USER.STU_LEFT_AT IS
    'Optional timestamp when the account left the store operation';
COMMENT ON COLUMN BEX_STORE_USER.STU_CREATED_AT IS
    'Timestamp when the operational participation record was created';
COMMENT ON COLUMN BEX_STORE_USER.STU_UPDATED_AT IS
    'Timestamp of the last effective change to the operational participation';
COMMENT ON COLUMN BEX_STORE_USER.STU_CREATED_BY IS
    'Optional account identifier of the actor that created the record';
COMMENT ON COLUMN BEX_STORE_USER.STU_UPDATED_BY IS
    'Optional account identifier of the actor that last changed the record';

CREATE UNIQUE INDEX UK_STU_STORE_ACCOUNT_ACTIVE
    ON BEX_STORE_USER
    (
        CASE WHEN STU_STATUS = 'ACTIVE' THEN STR_ID END,
        CASE WHEN STU_STATUS = 'ACTIVE' THEN ACC_ID END
    );

CREATE INDEX IDX_STORE_USER_STORE ON BEX_STORE_USER (STR_ID);
CREATE INDEX IDX_STORE_USER_ACCOUNT ON BEX_STORE_USER (ACC_ID);
CREATE INDEX IDX_STORE_USER_ROLE ON BEX_STORE_USER (STU_ROLE_CODE);
CREATE INDEX IDX_STORE_USER_STATUS ON BEX_STORE_USER (STU_STATUS);

DECLARE
    l_table_count      PLS_INTEGER;
    l_column_count     PLS_INTEGER;
    l_constraint_count PLS_INTEGER;
    l_index_count      PLS_INTEGER;
BEGIN
    SELECT COUNT(*) INTO l_table_count
      FROM USER_TABLES WHERE TABLE_NAME = 'BEX_STORE_USER';
    SELECT COUNT(*) INTO l_column_count
      FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BEX_STORE_USER';
    SELECT COUNT(*) INTO l_constraint_count
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'BEX_STORE_USER'
       AND CONSTRAINT_NAME IN
           ('PK_STORE_USER', 'UK_STORE_USER_PUBLIC_ID', 'FK_STU_STORE',
            'FK_STU_ACCOUNT', 'FK_STU_CREATED_BY_ACCOUNT',
            'FK_STU_UPDATED_BY_ACCOUNT', 'CK_STU_ROLE_CODE', 'CK_STU_STATUS');
    SELECT COUNT(*) INTO l_index_count
      FROM USER_INDEXES
     WHERE TABLE_NAME = 'BEX_STORE_USER'
       AND INDEX_NAME IN
           ('UK_STU_STORE_ACCOUNT_ACTIVE', 'IDX_STORE_USER_STORE',
            'IDX_STORE_USER_ACCOUNT', 'IDX_STORE_USER_ROLE', 'IDX_STORE_USER_STATUS');

    IF l_table_count <> 1 OR l_column_count <> 12 OR
       l_constraint_count <> 8 OR l_index_count <> 5 THEN
        RAISE_APPLICATION_ERROR(-20003, 'BEX_STORE_USER physical structure validation failed');
    END IF;
END;
/
