WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_STORE_PLAN(
  STP_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,STP_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  STP_CODE VARCHAR2(50 CHAR) NOT NULL,STP_NAME VARCHAR2(100 CHAR) NOT NULL,
  STP_DESCRIPTION VARCHAR2(500 CHAR),STP_PRICE NUMBER(12,2),STP_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  STP_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,STP_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  STP_CREATED_BY NUMBER(19),STP_UPDATED_BY NUMBER(19),
  CONSTRAINT PK_STORE_PLAN PRIMARY KEY(STP_ID),CONSTRAINT UK_STORE_PLAN_PUBLIC_ID UNIQUE(STP_PUBLIC_ID),
  CONSTRAINT UK_STORE_PLAN_CODE UNIQUE(STP_CODE),CONSTRAINT CK_STP_CODE CHECK(STP_CODE IN('FREE','PLUS','PREMIUM')),
  CONSTRAINT CK_STP_PRICE CHECK(STP_PRICE IS NULL OR STP_PRICE>=0),CONSTRAINT CK_STP_STATUS CHECK(STP_STATUS IN('ACTIVE','INACTIVE'))
);
CREATE INDEX IDX_STORE_PLAN_STATUS ON BEX_STORE_PLAN(STP_STATUS);
MERGE INTO BEX_STORE_PLAN d USING(
  SELECT 'FREE' code,'Free' name,0 price FROM dual UNION ALL SELECT 'PLUS','Plus',NULL FROM dual UNION ALL SELECT 'PREMIUM','Premium',NULL FROM dual
)s ON(d.STP_CODE=s.code)WHEN NOT MATCHED THEN INSERT(STP_PUBLIC_ID,STP_CODE,STP_NAME,STP_PRICE)
VALUES(LOWER(RAWTOHEX(SYS_GUID())),s.code,s.name,s.price);
PROMPT BEX_STORE_PLAN structure installed successfully.
