WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_STORE_EVENT(
  STE_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,STE_PUBLIC_ID CHAR(32 CHAR) NOT NULL,STR_ID NUMBER(19) NOT NULL,
  STE_NAME VARCHAR2(200 CHAR) NOT NULL,STE_DESCRIPTION VARCHAR2(1000 CHAR),STE_START_AT TIMESTAMP(6) NOT NULL,
  STE_END_AT TIMESTAMP(6) NOT NULL,STE_STATUS VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
  STE_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,STE_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  STE_CREATED_BY NUMBER(19),STE_UPDATED_BY NUMBER(19),
  CONSTRAINT PK_STORE_EVENT PRIMARY KEY(STE_ID),CONSTRAINT UK_STORE_EVENT_PUBLIC_ID UNIQUE(STE_PUBLIC_ID),
  CONSTRAINT FK_STE_STORE FOREIGN KEY(STR_ID)REFERENCES BEX_STORE(STR_ID),
  CONSTRAINT FK_STE_CREATED_BY FOREIGN KEY(STE_CREATED_BY)REFERENCES BEX_ACCOUNT(ACC_ID),
  CONSTRAINT FK_STE_UPDATED_BY FOREIGN KEY(STE_UPDATED_BY)REFERENCES BEX_ACCOUNT(ACC_ID),
  CONSTRAINT CK_STE_PERIOD CHECK(STE_END_AT>=STE_START_AT),
  CONSTRAINT CK_STE_STATUS CHECK(STE_STATUS IN('DRAFT','ACTIVE','CLOSED','CANCELLED'))
);
CREATE INDEX IDX_STORE_EVENT_STORE ON BEX_STORE_EVENT(STR_ID);
CREATE INDEX IDX_STORE_EVENT_STATUS ON BEX_STORE_EVENT(STE_STATUS);
CREATE INDEX IDX_STORE_EVENT_PERIOD ON BEX_STORE_EVENT(STE_START_AT,STE_END_AT);
PROMPT BEX_STORE_EVENT structure installed successfully.
