WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE OR REPLACE VIEW BEX_STORE_BALANCE AS
SELECT STR_ID,
  SUM(CASE WHEN SBT_TYPE='SALE_HOLD' AND SBT_DIRECTION='CREDIT' THEN SBT_AMOUNT
           WHEN SBT_TYPE='HOLD_RELEASE' AND SBT_DIRECTION='DEBIT' THEN -SBT_AMOUNT ELSE 0 END) SBL_BLOCKED_AMOUNT,
  SUM(CASE WHEN SBT_TYPE='HOLD_RELEASE' AND SBT_DIRECTION='CREDIT' THEN SBT_AMOUNT
           WHEN SBT_TYPE='PAYOUT_RESERVE' AND SBT_DIRECTION='DEBIT' THEN -SBT_AMOUNT
           WHEN SBT_TYPE='PAYOUT_RESTORE' AND SBT_DIRECTION='CREDIT' THEN SBT_AMOUNT ELSE 0 END) SBL_AVAILABLE_AMOUNT,
  SUM(CASE WHEN SBT_TYPE='PAYOUT_RESERVE' THEN SBT_AMOUNT
           WHEN SBT_TYPE IN('PAYOUT_RESTORE','PAYOUT_PAID') THEN -SBT_AMOUNT ELSE 0 END) SBL_PENDING_PAYOUT_AMOUNT,
  SUM(CASE WHEN SBT_TYPE='PAYOUT_PAID' THEN SBT_AMOUNT ELSE 0 END) SBL_PAID_AMOUNT
FROM BEX_STORE_BALANCE_TRANSACTION WHERE SBT_STATUS='POSTED' GROUP BY STR_ID;
COMMENT ON TABLE BEX_STORE_BALANCE IS 'Read-only balance projection derived exclusively from the ledger';
PROMPT BEX_STORE_BALANCE view installed successfully.
