CREATE OR REPLACE PACKAGE BODY rol_query_pkg AS
  FUNCTION get_by_code(p_code VARCHAR2,p_require_active BOOLEAN DEFAULT TRUE)RETURN t_record IS r t_record;
  BEGIN BEGIN SELECT ROL_ID,ROL_PUBLIC_ID,ROL_CODE,ROL_NAME,ROL_DESCRIPTION,ROL_STATUS INTO r
    FROM BEX_ROLE WHERE ROL_CODE=UPPER(TRIM(p_code));EXCEPTION WHEN NO_DATA_FOUND THEN RAISE e_not_found;END;
    IF p_require_active AND r.status<>'ACTIVE'THEN RAISE e_inactive;END IF;RETURN r;END;
  FUNCTION list_active RETURN t_records IS x t_records;n PLS_INTEGER:=0;BEGIN FOR q IN(
    SELECT ROL_CODE FROM BEX_ROLE WHERE ROL_STATUS='ACTIVE' ORDER BY ROL_CODE)LOOP n:=n+1;x(n):=get_by_code(q.ROL_CODE);END LOOP;RETURN x;END;
END rol_query_pkg;
/
