CREATE OR REPLACE PACKAGE BODY sbt_rule_pkg AS
  PROCEDURE validate_movement(p_type VARCHAR2,p_amount NUMBER,p_direction VARCHAR2) IS
    t VARCHAR2(50):=UPPER(TRIM(p_type));d VARCHAR2(10):=UPPER(TRIM(p_direction));
  BEGIN IF t NOT IN('SALE_HOLD','HOLD_RELEASE','PAYOUT_RESERVE','PAYOUT_RESTORE','PAYOUT_PAID')
    OR p_amount<=0 OR d NOT IN('CREDIT','DEBIT')
    OR(t='SALE_HOLD' AND d<>'CREDIT') OR(t IN('PAYOUT_RESERVE','PAYOUT_PAID') AND d<>'DEBIT')
    OR(t='PAYOUT_RESTORE' AND d<>'CREDIT') THEN RAISE e_invalid;END IF;END;
END sbt_rule_pkg;
/
