WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_RETURN_REQUEST(
  RRQ_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  RRQ_PUBLIC_ID CHAR(32 CHAR) NOT NULL,ORD_ID NUMBER(19) NOT NULL,STR_ID NUMBER(19) NOT NULL,PFL_ID NUMBER(19) NOT NULL,
  RRQ_REASON_CODE VARCHAR2(50 CHAR) NOT NULL,RRQ_DESCRIPTION VARCHAR2(2000 CHAR),
  RRQ_STATUS VARCHAR2(20 CHAR) DEFAULT 'OPEN' NOT NULL,RRQ_RESULT VARCHAR2(50 CHAR),
  RRQ_PRIORITY VARCHAR2(20 CHAR) DEFAULT 'NORMAL' NOT NULL,RRQ_SEVERITY VARCHAR2(20 CHAR) DEFAULT 'NORMAL' NOT NULL,
  RRQ_SOURCE VARCHAR2(50 CHAR) DEFAULT 'CUSTOMER' NOT NULL,RRQ_REQUESTED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  RRQ_DECIDED_AT TIMESTAMP(6),RRQ_DECIDED_BY NUMBER(19),RRQ_CLOSED_AT TIMESTAMP(6),RRQ_CLOSED_BY NUMBER(19),
  RRQ_STORE_RESPONSE VARCHAR2(2000 CHAR),RRQ_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  RRQ_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,RRQ_CREATED_BY NUMBER(19),RRQ_UPDATED_BY NUMBER(19),
  CONSTRAINT PK_RETURN_REQUEST PRIMARY KEY(RRQ_ID),CONSTRAINT UK_RETURN_REQUEST_PUBLIC_ID UNIQUE(RRQ_PUBLIC_ID),
  CONSTRAINT FK_RRQ_ORDER FOREIGN KEY(ORD_ID) REFERENCES BEX_ORDER(ORD_ID),
  CONSTRAINT FK_RRQ_STORE FOREIGN KEY(STR_ID) REFERENCES BEX_STORE(STR_ID),
  CONSTRAINT FK_RRQ_PROFILE FOREIGN KEY(PFL_ID) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT FK_RRQ_DECIDED_BY FOREIGN KEY(RRQ_DECIDED_BY) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT FK_RRQ_CLOSED_BY FOREIGN KEY(RRQ_CLOSED_BY) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT FK_RRQ_CREATED_BY FOREIGN KEY(RRQ_CREATED_BY) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT FK_RRQ_UPDATED_BY FOREIGN KEY(RRQ_UPDATED_BY) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT CK_RRQ_STATUS CHECK(RRQ_STATUS IN('OPEN','UNDER_REVIEW','DECIDED','CLOSED')),
  CONSTRAINT CK_RRQ_PRIORITY CHECK(RRQ_PRIORITY IN('LOW','NORMAL','HIGH','URGENT')),
  CONSTRAINT CK_RRQ_SEVERITY CHECK(RRQ_SEVERITY IN('LOW','NORMAL','HIGH','CRITICAL')),
  CONSTRAINT CK_RRQ_SOURCE CHECK(RRQ_SOURCE IN('CUSTOMER','STORE','SYSTEM','ADMIN')),
  CONSTRAINT CK_RRQ_DECISION CHECK((RRQ_STATUS IN('OPEN','UNDER_REVIEW') AND RRQ_RESULT IS NULL AND RRQ_DECIDED_AT IS NULL AND RRQ_DECIDED_BY IS NULL)
    OR(RRQ_STATUS IN('DECIDED','CLOSED') AND RRQ_RESULT IS NOT NULL AND RRQ_DECIDED_AT IS NOT NULL AND RRQ_DECIDED_BY IS NOT NULL)),
  CONSTRAINT CK_RRQ_CLOSURE CHECK((RRQ_STATUS<>'CLOSED' AND RRQ_CLOSED_AT IS NULL AND RRQ_CLOSED_BY IS NULL)
    OR(RRQ_STATUS='CLOSED' AND RRQ_CLOSED_AT IS NOT NULL AND RRQ_CLOSED_BY IS NOT NULL))
);
CREATE INDEX IDX_RETURN_REQUEST_ORDER ON BEX_RETURN_REQUEST(ORD_ID);
CREATE INDEX IDX_RETURN_REQUEST_STORE ON BEX_RETURN_REQUEST(STR_ID);
CREATE INDEX IDX_RETURN_REQUEST_STATUS ON BEX_RETURN_REQUEST(RRQ_STATUS);
CREATE INDEX IDX_RETURN_REQUEST_SOURCE ON BEX_RETURN_REQUEST(RRQ_SOURCE);
CREATE INDEX IDX_RETURN_REQUEST_SEVERITY ON BEX_RETURN_REQUEST(RRQ_SEVERITY);
CREATE INDEX IDX_RETURN_REQUEST_PRIORITY ON BEX_RETURN_REQUEST(RRQ_PRIORITY);
PROMPT BEX_RETURN_REQUEST structure installed successfully.
