WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_STORE_REVIEW(
  SRV_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,SRV_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  ORD_ID NUMBER(19) NOT NULL,STR_ID NUMBER(19) NOT NULL,PFL_ID NUMBER(19) NOT NULL,
  SRV_OVERALL_RATE NUMBER(1) NOT NULL,SRV_PRODUCT_MATCH_RATE NUMBER(1),SRV_CONSERVATION_RATE NUMBER(1),
  SRV_SERVICE_RATE NUMBER(1),SRV_DELIVERY_RATE NUMBER(1),SRV_PACKAGING_RATE NUMBER(1),
  SRV_WOULD_BUY_AGAIN CHAR(1 CHAR),SRV_COMMENT VARCHAR2(2000 CHAR),SRV_STORE_REPLY VARCHAR2(2000 CHAR),
  SRV_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,SRV_REVIEWED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  SRV_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,SRV_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  SRV_CREATED_BY NUMBER(19),SRV_UPDATED_BY NUMBER(19),
  CONSTRAINT PK_STORE_REVIEW PRIMARY KEY(SRV_ID),CONSTRAINT UK_STORE_REVIEW_PUBLIC_ID UNIQUE(SRV_PUBLIC_ID),
  CONSTRAINT UK_STORE_REVIEW_ORDER_STORE UNIQUE(ORD_ID,STR_ID),
  CONSTRAINT FK_SRV_ORDER FOREIGN KEY(ORD_ID) REFERENCES BEX_ORDER(ORD_ID),
  CONSTRAINT FK_SRV_STORE FOREIGN KEY(STR_ID) REFERENCES BEX_STORE(STR_ID),
  CONSTRAINT FK_SRV_PROFILE FOREIGN KEY(PFL_ID) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT FK_SRV_CREATED_BY FOREIGN KEY(SRV_CREATED_BY) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT FK_SRV_UPDATED_BY FOREIGN KEY(SRV_UPDATED_BY) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT CK_SRV_OVERALL CHECK(SRV_OVERALL_RATE BETWEEN 1 AND 5),
  CONSTRAINT CK_SRV_PRODUCT_MATCH CHECK(SRV_PRODUCT_MATCH_RATE IS NULL OR SRV_PRODUCT_MATCH_RATE BETWEEN 1 AND 5),
  CONSTRAINT CK_SRV_CONSERVATION CHECK(SRV_CONSERVATION_RATE IS NULL OR SRV_CONSERVATION_RATE BETWEEN 1 AND 5),
  CONSTRAINT CK_SRV_SERVICE CHECK(SRV_SERVICE_RATE IS NULL OR SRV_SERVICE_RATE BETWEEN 1 AND 5),
  CONSTRAINT CK_SRV_DELIVERY CHECK(SRV_DELIVERY_RATE IS NULL OR SRV_DELIVERY_RATE BETWEEN 1 AND 5),
  CONSTRAINT CK_SRV_PACKAGING CHECK(SRV_PACKAGING_RATE IS NULL OR SRV_PACKAGING_RATE BETWEEN 1 AND 5),
  CONSTRAINT CK_SRV_BUY_AGAIN CHECK(SRV_WOULD_BUY_AGAIN IS NULL OR SRV_WOULD_BUY_AGAIN IN('Y','N')),
  CONSTRAINT CK_SRV_STATUS CHECK(SRV_STATUS IN('ACTIVE','HIDDEN'))
);
CREATE INDEX IDX_STORE_REVIEW_STORE ON BEX_STORE_REVIEW(STR_ID);
CREATE INDEX IDX_STORE_REVIEW_RATE ON BEX_STORE_REVIEW(SRV_OVERALL_RATE);
PROMPT BEX_STORE_REVIEW structure installed successfully.
