WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_RETURN_ATTACHMENT(
  RAT_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,RAT_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  RRQ_ID NUMBER(19) NOT NULL,PFL_ID NUMBER(19) NOT NULL,RAT_TYPE VARCHAR2(50 CHAR) NOT NULL,
  RAT_URL VARCHAR2(1000 CHAR) NOT NULL,RAT_FILENAME VARCHAR2(255 CHAR),RAT_MIME_TYPE VARCHAR2(100 CHAR),
  RAT_SIZE_BYTES NUMBER(19),RAT_DESCRIPTION VARCHAR2(2000 CHAR),RAT_UPLOADED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  RAT_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,RAT_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  RAT_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,RAT_CREATED_BY NUMBER(19),RAT_UPDATED_BY NUMBER(19),
  CONSTRAINT PK_RETURN_ATTACHMENT PRIMARY KEY(RAT_ID),CONSTRAINT UK_RETURN_ATTACHMENT_PUBLIC_ID UNIQUE(RAT_PUBLIC_ID),
  CONSTRAINT FK_RAT_REQUEST FOREIGN KEY(RRQ_ID) REFERENCES BEX_RETURN_REQUEST(RRQ_ID),
  CONSTRAINT FK_RAT_PROFILE FOREIGN KEY(PFL_ID) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT FK_RAT_CREATED_BY FOREIGN KEY(RAT_CREATED_BY) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT FK_RAT_UPDATED_BY FOREIGN KEY(RAT_UPDATED_BY) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT CK_RAT_TYPE CHECK(RAT_TYPE IN('PHOTO','VIDEO','RECEIPT','PACKAGE','LABEL','DOCUMENT','OTHER')),
  CONSTRAINT CK_RAT_SIZE CHECK(RAT_SIZE_BYTES IS NULL OR RAT_SIZE_BYTES>0),
  CONSTRAINT CK_RAT_STATUS CHECK(RAT_STATUS IN('ACTIVE','HIDDEN'))
);
CREATE INDEX IDX_RETURN_ATTACHMENT_REQUEST ON BEX_RETURN_ATTACHMENT(RRQ_ID);
CREATE INDEX IDX_RETURN_ATTACHMENT_PROFILE ON BEX_RETURN_ATTACHMENT(PFL_ID);
CREATE INDEX IDX_RETURN_ATTACHMENT_TYPE ON BEX_RETURN_ATTACHMENT(RAT_TYPE);
CREATE INDEX IDX_RETURN_ATTACHMENT_STATUS ON BEX_RETURN_ATTACHMENT(RAT_STATUS);
PROMPT BEX_RETURN_ATTACHMENT structure installed successfully.
