WHENEVER SQLERROR EXIT SQL.SQLCODE;

DECLARE
  l_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO l_count FROM USER_OBJECTS
   WHERE OBJECT_NAME='BEX_PRODUCT';
  IF l_count>0 THEN
    RAISE_APPLICATION_ERROR(-20000,'BEX_PRODUCT already exists or conflicts');
  END IF;
  SELECT COUNT(*) INTO l_count FROM USER_TABLES
   WHERE TABLE_NAME IN ('BEX_STORE','BEX_CATEGORY','BEX_BRAND');
  IF l_count<>3 THEN
    RAISE_APPLICATION_ERROR(
      -20001,
      'BEX_STORE, BEX_CATEGORY and BEX_BRAND must exist'
    );
  END IF;
END;
/

CREATE TABLE BEX_PRODUCT
(
  PRD_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY
    (START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE),
  PRD_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  STR_ID NUMBER(19) NOT NULL,
  CAT_ID NUMBER(19) NOT NULL,
  BRD_ID NUMBER(19),
  PRD_TITLE VARCHAR2(200 CHAR) NOT NULL,
  PRD_SLUG VARCHAR2(200 CHAR) NOT NULL,
  PRD_DESCRIPTION VARCHAR2(4000 CHAR),
  PRD_PRICE NUMBER(12,2) NOT NULL,
  PRD_QUANTITY NUMBER(12) NOT NULL,
  PRD_CONDITION VARCHAR2(20 CHAR) NOT NULL,
  PRD_WEIGHT NUMBER(10,3),
  PRD_WIDTH NUMBER(10,3),
  PRD_HEIGHT NUMBER(10,3),
  PRD_LENGTH NUMBER(10,3),
  PRD_STATUS VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
  PRD_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PRD_CREATED_BY NUMBER,
  PRD_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PRD_UPDATED_BY NUMBER,
  CONSTRAINT PK_PRODUCT PRIMARY KEY(PRD_ID),
  CONSTRAINT UK_PRODUCT_PUBLIC_ID UNIQUE(PRD_PUBLIC_ID),
  CONSTRAINT UK_PRODUCT_STORE_SLUG UNIQUE(STR_ID,PRD_SLUG),
  CONSTRAINT UK_PRODUCT_ID_STORE UNIQUE(PRD_ID,STR_ID),
  CONSTRAINT FK_PRD_STORE FOREIGN KEY(STR_ID) REFERENCES BEX_STORE(STR_ID),
  CONSTRAINT FK_PRD_CATEGORY FOREIGN KEY(CAT_ID) REFERENCES BEX_CATEGORY(CAT_ID),
  CONSTRAINT FK_PRD_BRAND FOREIGN KEY(BRD_ID) REFERENCES BEX_BRAND(BRD_ID),
  CONSTRAINT CK_PRD_PRICE CHECK(PRD_PRICE>=0),
  CONSTRAINT CK_PRD_QUANTITY CHECK(PRD_QUANTITY>=0),
  CONSTRAINT CK_PRD_CONDITION CHECK(
    PRD_CONDITION IN ('NEW','LIKE_NEW','GOOD','FAIR')
  ),
  CONSTRAINT CK_PRD_WEIGHT CHECK(PRD_WEIGHT IS NULL OR PRD_WEIGHT>0),
  CONSTRAINT CK_PRD_DIMENSIONS_POSITIVE CHECK(
    (PRD_WIDTH IS NULL OR PRD_WIDTH>0)
    AND (PRD_HEIGHT IS NULL OR PRD_HEIGHT>0)
    AND (PRD_LENGTH IS NULL OR PRD_LENGTH>0)
  ),
  CONSTRAINT CK_PRD_DIMENSIONS_SET CHECK(
    (PRD_WIDTH IS NULL AND PRD_HEIGHT IS NULL AND PRD_LENGTH IS NULL)
    OR
    (PRD_WIDTH IS NOT NULL AND PRD_HEIGHT IS NOT NULL AND PRD_LENGTH IS NOT NULL)
  ),
  CONSTRAINT CK_PRD_STATUS CHECK(
    PRD_STATUS IN ('DRAFT','ACTIVE','INACTIVE','SOLD','ARCHIVED')
  )
);

CREATE INDEX IDX_PRODUCT_CATEGORY ON BEX_PRODUCT(CAT_ID);
CREATE INDEX IDX_PRODUCT_BRAND ON BEX_PRODUCT(BRD_ID);
CREATE INDEX IDX_PRODUCT_STATUS ON BEX_PRODUCT(PRD_STATUS);
CREATE INDEX IDX_PRODUCT_PRICE ON BEX_PRODUCT(PRD_PRICE);

COMMENT ON TABLE BEX_PRODUCT IS 'Catalog item presented to users as an Achado';
COMMENT ON COLUMN BEX_PRODUCT.PRD_ID IS 'Internal Oracle identity';
COMMENT ON COLUMN BEX_PRODUCT.PRD_PUBLIC_ID IS 'Immutable public identifier';
COMMENT ON COLUMN BEX_PRODUCT.STR_ID IS 'Store that owns the product';
COMMENT ON COLUMN BEX_PRODUCT.CAT_ID IS 'Required category classification';
COMMENT ON COLUMN BEX_PRODUCT.BRD_ID IS 'Optional brand classification';
COMMENT ON COLUMN BEX_PRODUCT.PRD_TITLE IS 'Public product title';
COMMENT ON COLUMN BEX_PRODUCT.PRD_SLUG IS 'Canonical slug unique inside the store';
COMMENT ON COLUMN BEX_PRODUCT.PRD_DESCRIPTION IS 'Optional public description';
COMMENT ON COLUMN BEX_PRODUCT.PRD_PRICE IS 'Current nonnegative advertised price';
COMMENT ON COLUMN BEX_PRODUCT.PRD_QUANTITY IS 'Nonnegative advertised quantity';
COMMENT ON COLUMN BEX_PRODUCT.PRD_CONDITION IS 'Physical condition code';
COMMENT ON COLUMN BEX_PRODUCT.PRD_WEIGHT IS 'Optional positive weight';
COMMENT ON COLUMN BEX_PRODUCT.PRD_WIDTH IS 'Optional positive width';
COMMENT ON COLUMN BEX_PRODUCT.PRD_HEIGHT IS 'Optional positive height';
COMMENT ON COLUMN BEX_PRODUCT.PRD_LENGTH IS 'Optional positive length';
COMMENT ON COLUMN BEX_PRODUCT.PRD_STATUS IS 'Current product lifecycle status';
COMMENT ON COLUMN BEX_PRODUCT.PRD_CREATED_AT IS 'Creation timestamp';
COMMENT ON COLUMN BEX_PRODUCT.PRD_CREATED_BY IS 'Optional creator technical actor';
COMMENT ON COLUMN BEX_PRODUCT.PRD_UPDATED_AT IS 'Last update timestamp';
COMMENT ON COLUMN BEX_PRODUCT.PRD_UPDATED_BY IS 'Optional updater technical actor';

DECLARE
  l_columns PLS_INTEGER;
  l_constraints PLS_INTEGER;
  l_indexes PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO l_columns FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME='BEX_PRODUCT';
  SELECT COUNT(*) INTO l_constraints FROM USER_CONSTRAINTS
   WHERE TABLE_NAME='BEX_PRODUCT'
     AND CONSTRAINT_NAME IN (
       'PK_PRODUCT','UK_PRODUCT_PUBLIC_ID','UK_PRODUCT_STORE_SLUG',
       'UK_PRODUCT_ID_STORE',
       'FK_PRD_STORE','FK_PRD_CATEGORY','FK_PRD_BRAND',
       'CK_PRD_PRICE','CK_PRD_QUANTITY','CK_PRD_CONDITION',
       'CK_PRD_WEIGHT','CK_PRD_DIMENSIONS_POSITIVE',
       'CK_PRD_DIMENSIONS_SET','CK_PRD_STATUS'
     );
  SELECT COUNT(*) INTO l_indexes FROM USER_INDEXES
   WHERE TABLE_NAME='BEX_PRODUCT'
     AND INDEX_NAME IN (
       'IDX_PRODUCT_CATEGORY','IDX_PRODUCT_BRAND',
       'IDX_PRODUCT_STATUS','IDX_PRODUCT_PRICE'
     );
  IF l_columns<>20 OR l_constraints<>14 OR l_indexes<>4 THEN
    RAISE_APPLICATION_ERROR(-20002,'BEX_PRODUCT physical validation failed');
  END IF;
END;
/
