WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_PRODUCT_QUESTION (
  PQA_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  PQA_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  PRD_ID NUMBER(19) NOT NULL,
  STR_ID NUMBER(19) NOT NULL,
  PFL_QUESTION_BY NUMBER(19) NOT NULL,
  PFL_ANSWERED_BY NUMBER(19),
  PQA_QUESTION_TEXT VARCHAR2(4000 CHAR) NOT NULL,
  PQA_ANSWER_TEXT VARCHAR2(4000 CHAR),
  PQA_ASKED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PQA_ANSWERED_AT TIMESTAMP(6),
  PQA_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  PQA_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PQA_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PQA_CREATED_BY NUMBER,
  PQA_UPDATED_BY NUMBER,
  CONSTRAINT PK_PRODUCT_QUESTION PRIMARY KEY(PQA_ID),
  CONSTRAINT UK_PRODUCT_QUESTION_PUBLIC_ID UNIQUE(PQA_PUBLIC_ID),
  CONSTRAINT FK_PQA_PRODUCT_STORE FOREIGN KEY(PRD_ID,STR_ID)
    REFERENCES BEX_PRODUCT(PRD_ID,STR_ID),
  CONSTRAINT FK_PQA_QUESTION_BY FOREIGN KEY(PFL_QUESTION_BY)
    REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT FK_PQA_ANSWERED_BY FOREIGN KEY(PFL_ANSWERED_BY)
    REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT CK_PQA_STATUS CHECK(PQA_STATUS IN ('ACTIVE','HIDDEN','MODERATED')),
  CONSTRAINT CK_PQA_ANSWER_STATE CHECK(
    (PQA_ANSWER_TEXT IS NULL AND PFL_ANSWERED_BY IS NULL AND PQA_ANSWERED_AT IS NULL)
    OR
    (PQA_ANSWER_TEXT IS NOT NULL AND PFL_ANSWERED_BY IS NOT NULL AND PQA_ANSWERED_AT IS NOT NULL)
  )
);
CREATE INDEX IDX_PRODUCT_QUESTION_PRODUCT ON BEX_PRODUCT_QUESTION(PRD_ID);
CREATE INDEX IDX_PRODUCT_QUESTION_STORE ON BEX_PRODUCT_QUESTION(STR_ID);
CREATE INDEX IDX_PRODUCT_QUESTION_QUESTION_BY ON BEX_PRODUCT_QUESTION(PFL_QUESTION_BY);
CREATE INDEX IDX_PRODUCT_QUESTION_ANSWERED_BY ON BEX_PRODUCT_QUESTION(PFL_ANSWERED_BY);
CREATE INDEX IDX_PRODUCT_QUESTION_STATUS ON BEX_PRODUCT_QUESTION(PQA_STATUS);
COMMENT ON TABLE BEX_PRODUCT_QUESTION IS 'Public pre-sale question and optional store answer';
COMMENT ON COLUMN BEX_PRODUCT_QUESTION.PQA_ID IS 'Internal Oracle identity';
COMMENT ON COLUMN BEX_PRODUCT_QUESTION.PQA_PUBLIC_ID IS 'Immutable public identifier';
COMMENT ON COLUMN BEX_PRODUCT_QUESTION.PRD_ID IS 'Questioned product';
COMMENT ON COLUMN BEX_PRODUCT_QUESTION.STR_ID IS 'Store preserved and constrained from product';
COMMENT ON COLUMN BEX_PRODUCT_QUESTION.PFL_QUESTION_BY IS 'Profile that asked the question';
COMMENT ON COLUMN BEX_PRODUCT_QUESTION.PFL_ANSWERED_BY IS 'Optional answering profile';
COMMENT ON COLUMN BEX_PRODUCT_QUESTION.PQA_QUESTION_TEXT IS 'Public question text';
COMMENT ON COLUMN BEX_PRODUCT_QUESTION.PQA_ANSWER_TEXT IS 'Optional public answer text';
COMMENT ON COLUMN BEX_PRODUCT_QUESTION.PQA_ASKED_AT IS 'Question timestamp';
COMMENT ON COLUMN BEX_PRODUCT_QUESTION.PQA_ANSWERED_AT IS 'Optional answer timestamp';
COMMENT ON COLUMN BEX_PRODUCT_QUESTION.PQA_STATUS IS 'Publication and moderation status';
COMMENT ON COLUMN BEX_PRODUCT_QUESTION.PQA_CREATED_AT IS 'Creation timestamp';
COMMENT ON COLUMN BEX_PRODUCT_QUESTION.PQA_UPDATED_AT IS 'Last update timestamp';
COMMENT ON COLUMN BEX_PRODUCT_QUESTION.PQA_CREATED_BY IS 'Optional creator technical actor';
COMMENT ON COLUMN BEX_PRODUCT_QUESTION.PQA_UPDATED_BY IS 'Optional updater technical actor';
PROMPT BEX_PRODUCT_QUESTION structure installed successfully.
