WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_PRODUCT_IMAGE (
  PIM_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  PIM_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  PRD_ID NUMBER(19) NOT NULL,
  PIM_URL VARCHAR2(1000 CHAR) NOT NULL,
  PIM_ALT_TEXT VARCHAR2(200 CHAR),
  PIM_SORT_ORDER NUMBER(12) NOT NULL,
  PIM_IS_PRIMARY NUMBER(1) DEFAULT 0 NOT NULL,
  PIM_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  PIM_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PIM_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PIM_CREATED_BY NUMBER,
  PIM_UPDATED_BY NUMBER,
  CONSTRAINT PK_PRODUCT_IMAGE PRIMARY KEY(PIM_ID),
  CONSTRAINT UK_PRODUCT_IMAGE_PUBLIC_ID UNIQUE(PIM_PUBLIC_ID),
  CONSTRAINT FK_PIM_PRODUCT FOREIGN KEY(PRD_ID) REFERENCES BEX_PRODUCT(PRD_ID),
  CONSTRAINT CK_PIM_SORT_ORDER CHECK(PIM_SORT_ORDER>=0),
  CONSTRAINT CK_PIM_IS_PRIMARY CHECK(PIM_IS_PRIMARY IN (0,1)),
  CONSTRAINT CK_PIM_STATUS CHECK(PIM_STATUS IN ('ACTIVE','INACTIVE'))
);
CREATE INDEX IDX_PRODUCT_IMAGE_PRODUCT ON BEX_PRODUCT_IMAGE(PRD_ID);
CREATE UNIQUE INDEX IDX_PRODUCT_IMAGE_PRIMARY ON BEX_PRODUCT_IMAGE(
  CASE WHEN PIM_STATUS='ACTIVE' AND PIM_IS_PRIMARY=1 THEN PRD_ID END
);
CREATE INDEX IDX_PRODUCT_IMAGE_STATUS ON BEX_PRODUCT_IMAGE(PIM_STATUS);
COMMENT ON TABLE BEX_PRODUCT_IMAGE IS 'Ordered image metadata for a catalog product';
COMMENT ON COLUMN BEX_PRODUCT_IMAGE.PIM_ID IS 'Internal Oracle identity';
COMMENT ON COLUMN BEX_PRODUCT_IMAGE.PIM_PUBLIC_ID IS 'Immutable public identifier';
COMMENT ON COLUMN BEX_PRODUCT_IMAGE.PRD_ID IS 'Product that owns the image';
COMMENT ON COLUMN BEX_PRODUCT_IMAGE.PIM_URL IS 'External image URL';
COMMENT ON COLUMN BEX_PRODUCT_IMAGE.PIM_ALT_TEXT IS 'Optional accessibility text';
COMMENT ON COLUMN BEX_PRODUCT_IMAGE.PIM_SORT_ORDER IS 'Nonnegative display order';
COMMENT ON COLUMN BEX_PRODUCT_IMAGE.PIM_IS_PRIMARY IS 'Primary image flag: 0 or 1';
COMMENT ON COLUMN BEX_PRODUCT_IMAGE.PIM_STATUS IS 'Logical lifecycle status';
COMMENT ON COLUMN BEX_PRODUCT_IMAGE.PIM_CREATED_AT IS 'Creation timestamp';
COMMENT ON COLUMN BEX_PRODUCT_IMAGE.PIM_UPDATED_AT IS 'Last update timestamp';
COMMENT ON COLUMN BEX_PRODUCT_IMAGE.PIM_CREATED_BY IS 'Optional creator technical actor';
COMMENT ON COLUMN BEX_PRODUCT_IMAGE.PIM_UPDATED_BY IS 'Optional updater technical actor';
PROMPT BEX_PRODUCT_IMAGE structure installed successfully.
