WHENEVER SQLERROR EXIT SQL.SQLCODE
DECLARE
  l_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO l_count FROM USER_CONSTRAINTS
   WHERE TABLE_NAME='BEX_PRODUCT' AND CONSTRAINT_NAME='UK_PRODUCT_ID_STORE';
  IF l_count=0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE BEX_PRODUCT ADD CONSTRAINT UK_PRODUCT_ID_STORE '||
      'UNIQUE(PRD_ID,STR_ID)';
  END IF;
END;
/
PROMPT PRODUCT question support installed successfully.
