SET SERVEROUTPUT ON SIZE UNLIMITED
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT Upgrading BEX_CATEGORY with hierarchy...

DECLARE
  l_count PLS_INTEGER;
  PROCEDURE add_column(p_name VARCHAR2,p_ddl VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO l_count FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME='BEX_CATEGORY' AND COLUMN_NAME=p_name;
    IF l_count=0 THEN EXECUTE IMMEDIATE p_ddl; END IF;
  END;
BEGIN
  add_column('CAT_PARENT_ID','ALTER TABLE BEX_CATEGORY ADD CAT_PARENT_ID NUMBER(19)');
  add_column('CAT_SORT_ORDER','ALTER TABLE BEX_CATEGORY ADD CAT_SORT_ORDER NUMBER(9) DEFAULT 0 NOT NULL');
  add_column('CAT_ACCEPTS_PRODUCTS','ALTER TABLE BEX_CATEGORY ADD CAT_ACCEPTS_PRODUCTS NUMBER(1) DEFAULT 1 NOT NULL');

  SELECT COUNT(*) INTO l_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME='FK_CATEGORY_PARENT';
  IF l_count=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BEX_CATEGORY ADD CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY(CAT_PARENT_ID) REFERENCES BEX_CATEGORY(CAT_ID)';END IF;
  SELECT COUNT(*) INTO l_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME='CK_CATEGORY_SORT_ORDER';
  IF l_count=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BEX_CATEGORY ADD CONSTRAINT CK_CATEGORY_SORT_ORDER CHECK(CAT_SORT_ORDER BETWEEN 0 AND 999999999)';END IF;
  SELECT COUNT(*) INTO l_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME='CK_CATEGORY_ACCEPTS_PRODUCTS';
  IF l_count=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BEX_CATEGORY ADD CONSTRAINT CK_CATEGORY_ACCEPTS_PRODUCTS CHECK(CAT_ACCEPTS_PRODUCTS IN(0,1))';END IF;
  SELECT COUNT(*) INTO l_count FROM USER_INDEXES WHERE INDEX_NAME='IDX_CATEGORY_PARENT';
  IF l_count=0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CATEGORY_PARENT ON BEX_CATEGORY(CAT_PARENT_ID,CAT_SORT_ORDER,CAT_NAME)';END IF;
END;
/

COMMENT ON COLUMN BEX_CATEGORY.CAT_PARENT_ID IS 'Optional parent category; NULL identifies a root category';
COMMENT ON COLUMN BEX_CATEGORY.CAT_SORT_ORDER IS 'Display order among categories with the same parent';
COMMENT ON COLUMN BEX_CATEGORY.CAT_ACCEPTS_PRODUCTS IS '1 when products may be associated directly with this category';

COMMIT;
