CREATE OR REPLACE PACKAGE BODY ntf_repository_pkg AS
  PROCEDURE insert_row(p t_row,o_id OUT NUMBER) IS BEGIN INSERT INTO BEX_NOTIFICATION(NTF_PUBLIC_ID,PFL_ID,NTF_TYPE,NTF_TITLE,NTF_BODY) VALUES(p.public_id,p.profile_id,p.notification_type,p.title,p.body) RETURNING NTF_ID INTO o_id; END;
  FUNCTION by_public(p_public_id VARCHAR2) RETURN t_row IS r t_row; BEGIN SELECT NTF_ID,NTF_PUBLIC_ID,PFL_ID,NTF_TYPE,NTF_TITLE,NTF_BODY,NTF_STATUS,NTF_CREATED_AT,NTF_READ_AT INTO r FROM BEX_NOTIFICATION WHERE NTF_PUBLIC_ID=LOWER(TRIM(p_public_id)); RETURN r; END;
  FUNCTION list_profile(p_profile_id NUMBER) RETURN t_rows IS x t_rows;n PLS_INTEGER:=0;BEGIN FOR q IN(SELECT NTF_PUBLIC_ID FROM BEX_NOTIFICATION WHERE PFL_ID=p_profile_id ORDER BY NTF_CREATED_AT DESC)LOOP n:=n+1;x(n):=by_public(q.NTF_PUBLIC_ID);END LOOP;RETURN x;END;
  PROCEDURE mark_read(p_id NUMBER) IS BEGIN UPDATE BEX_NOTIFICATION SET NTF_STATUS='READ',NTF_READ_AT=NVL(NTF_READ_AT,SYSTIMESTAMP) WHERE NTF_ID=p_id AND NTF_STATUS='UNREAD'; END;
END ntf_repository_pkg;
/
