CREATE OR REPLACE PACKAGE BODY srp_query_pkg AS
  FUNCTION get_store(p_store VARCHAR2)RETURN t_record IS r t_record;BEGIN BEGIN SELECT STR_PUBLIC_ID,SRP_OVERALL_RATE,
    SRP_REVIEW_COUNT,SRP_ORDER_COUNT,SRP_RETURN_REQUEST_COUNT,SRP_RETURN_RATE,SRP_WOULD_BUY_AGAIN_RATE,SRP_LAST_REVIEW_AT
    INTO r FROM BEX_STORE_REPUTATION WHERE STR_PUBLIC_ID=LOWER(TRIM(p_store));EXCEPTION WHEN NO_DATA_FOUND THEN RAISE e_not_found;END;RETURN r;END;
END srp_query_pkg;
/
