WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE OR REPLACE VIEW BEX_STORE_REPUTATION AS
WITH reviews AS(
  SELECT STR_ID,AVG(SRV_OVERALL_RATE) SRP_OVERALL_RATE,AVG(SRV_PRODUCT_MATCH_RATE) SRP_PRODUCT_MATCH_RATE,
    AVG(SRV_CONSERVATION_RATE) SRP_CONSERVATION_RATE,AVG(SRV_SERVICE_RATE) SRP_SERVICE_RATE,
    AVG(SRV_DELIVERY_RATE) SRP_DELIVERY_RATE,AVG(SRV_PACKAGING_RATE) SRP_PACKAGING_RATE,
    COUNT(*) SRP_REVIEW_COUNT,
    AVG(CASE SRV_WOULD_BUY_AGAIN WHEN 'Y' THEN 100 WHEN 'N' THEN 0 END) SRP_WOULD_BUY_AGAIN_RATE,
    MAX(SRV_REVIEWED_AT) SRP_LAST_REVIEW_AT
  FROM BEX_STORE_REVIEW WHERE SRV_STATUS='ACTIVE' GROUP BY STR_ID
),orders AS(
  SELECT i.STR_ID,COUNT(DISTINCT o.ORD_ID) SRP_ORDER_COUNT,MIN(o.ORD_CREATED_AT) SRP_FIRST_ORDER_AT,
    MAX(o.ORD_CREATED_AT) SRP_LAST_ORDER_AT
  FROM BEX_ORDER o JOIN BEX_ORDER_ITEM i ON i.ORD_ID=o.ORD_ID WHERE o.ORD_STATUS='COMPLETED' GROUP BY i.STR_ID
),returns AS(
  SELECT STR_ID,COUNT(*) SRP_RETURN_REQUEST_COUNT FROM BEX_RETURN_REQUEST GROUP BY STR_ID
)
SELECT s.STR_PUBLIC_ID AS SRP_PUBLIC_ID,s.STR_PUBLIC_ID,
  ROUND(r.SRP_OVERALL_RATE,2) SRP_OVERALL_RATE,ROUND(r.SRP_PRODUCT_MATCH_RATE,2) SRP_PRODUCT_MATCH_RATE,
  ROUND(r.SRP_CONSERVATION_RATE,2) SRP_CONSERVATION_RATE,ROUND(r.SRP_SERVICE_RATE,2) SRP_SERVICE_RATE,
  ROUND(r.SRP_DELIVERY_RATE,2) SRP_DELIVERY_RATE,ROUND(r.SRP_PACKAGING_RATE,2) SRP_PACKAGING_RATE,
  NVL(r.SRP_REVIEW_COUNT,0) SRP_REVIEW_COUNT,NVL(o.SRP_ORDER_COUNT,0) SRP_ORDER_COUNT,
  NVL(q.SRP_RETURN_REQUEST_COUNT,0) SRP_RETURN_REQUEST_COUNT,
  CASE WHEN NVL(o.SRP_ORDER_COUNT,0)=0 THEN NULL ELSE ROUND(100*NVL(q.SRP_RETURN_REQUEST_COUNT,0)/o.SRP_ORDER_COUNT,2) END SRP_RETURN_RATE,
  ROUND(r.SRP_WOULD_BUY_AGAIN_RATE,2) SRP_WOULD_BUY_AGAIN_RATE,
  CAST(NULL AS NUMBER) SRP_TRUST_SCORE,CAST(NULL AS NUMBER) SRP_REPUTATION_SCORE,
  CAST(NULL AS VARCHAR2(50)) SRP_LEVEL_CODE,CAST(NULL AS VARCHAR2(50)) SRP_BADGE_CODE,
  o.SRP_FIRST_ORDER_AT,o.SRP_LAST_ORDER_AT,r.SRP_LAST_REVIEW_AT,SYSTIMESTAMP SRP_LAST_RECALCULATED_AT
FROM BEX_STORE s LEFT JOIN reviews r ON r.STR_ID=s.STR_ID LEFT JOIN orders o ON o.STR_ID=s.STR_ID
LEFT JOIN returns q ON q.STR_ID=s.STR_ID;
PROMPT BEX_STORE_REPUTATION view installed successfully.
