SET SERVEROUTPUT ON SIZE UNLIMITED
SET VERIFY OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  l_key VARCHAR2(4000) := '&1';
BEGIN
  BEX_PUSH_BRIDGE_PKG.CONFIGURE_KEY(l_key);
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('SUCCESS - PUSH BRIDGE KEY CONFIGURED');
END;
/

EXIT SUCCESS COMMIT
