SET SERVEROUTPUT ON SIZE UNLIMITED
SET DEFINE OFF
SET ECHO ON
SET FEEDBACK ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL store_location_unicode_fix.log

@@install_store_location.sql

UPDATE BEX_STORE_LOCATION
   SET STL_CITY = UNISTR('S\00E3o Paulo'),
       STL_UPDATED_AT = SYS_EXTRACT_UTC(SYSTIMESTAMP)
 WHERE STL_STATE = 'SP'
   AND STL_CITY = 'S?o Paulo';

COMMIT;

PROMPT SUCCESS - STORE LOCATION UNICODE AND ENDPOINT FIXED

SPOOL OFF
EXIT SUCCESS COMMIT
