WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET SERVEROUTPUT ON
SET DEFINE OFF

PROMPT Ensuring payment-pending order runtime structures...

DECLARE
  l_count PLS_INTEGER;
BEGIN
  EXECUTE IMMEDIATE
    'ALTER TABLE BEX_ORDER MODIFY (ORD_STATUS DEFAULT ''PAYMENT_PENDING'')';
  EXECUTE IMMEDIATE 'ALTER TABLE BEX_ORDER MODIFY (ORD_PAID_AT NULL)';

  SELECT COUNT(*) INTO l_count FROM USER_CONSTRAINTS
  WHERE TABLE_NAME='BEX_ORDER' AND CONSTRAINT_NAME='CK_ORD_STATUS';
  IF l_count>0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BEX_ORDER DROP CONSTRAINT CK_ORD_STATUS';
  END IF;
  EXECUTE IMMEDIATE q'~
    ALTER TABLE BEX_ORDER ADD CONSTRAINT CK_ORD_STATUS CHECK(ORD_STATUS IN(
      'PAYMENT_PENDING','PAID','PROCESSING','SHIPPED','COMPLETED','CANCELLED'
    ))
  ~';

  SELECT COUNT(*) INTO l_count
  FROM USER_TABLES WHERE TABLE_NAME='BEX_ORDER_SHIPPING';
  IF l_count=0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE BEX_ORDER_SHIPPING(
        OSH_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
        OSH_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
        ORD_ID NUMBER(19) NOT NULL,
        STR_ID NUMBER(19) NOT NULL,
        PSO_ID NUMBER(19) NOT NULL,
        OSH_METHOD VARCHAR2(20 CHAR) NOT NULL,
        OSH_PRICE NUMBER(12,2) NOT NULL,
        OSH_DISTANCE_KM NUMBER(10,2),
        OSH_ESTIMATED_MIN_DAYS NUMBER(3) NOT NULL,
        OSH_ESTIMATED_MAX_DAYS NUMBER(3) NOT NULL,
        OSH_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        OSH_CREATED_BY NUMBER,
        CONSTRAINT PK_ORDER_SHIPPING PRIMARY KEY(OSH_ID),
        CONSTRAINT UK_ORDER_SHIPPING_PUBLIC UNIQUE(OSH_PUBLIC_ID),
        CONSTRAINT UK_ORDER_SHIPPING_STORE UNIQUE(ORD_ID,STR_ID),
        CONSTRAINT FK_OSH_ORDER FOREIGN KEY(ORD_ID) REFERENCES BEX_ORDER(ORD_ID),
        CONSTRAINT FK_OSH_STORE FOREIGN KEY(STR_ID) REFERENCES BEX_STORE(STR_ID),
        CONSTRAINT FK_OSH_OPTION FOREIGN KEY(PSO_ID)
          REFERENCES BEX_PURCHASE_SHIPPING_OPTION(PSO_ID),
        CONSTRAINT CK_OSH_METHOD CHECK(OSH_METHOD IN('PICKUP','LOCAL')),
        CONSTRAINT CK_OSH_PRICE CHECK(OSH_PRICE>=0),
        CONSTRAINT CK_OSH_DAYS CHECK(
          OSH_ESTIMATED_MIN_DAYS>=0
          AND OSH_ESTIMATED_MAX_DAYS>=OSH_ESTIMATED_MIN_DAYS
        )
      )
    ~';
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_ORDER_SHIPPING_ORDER ON BEX_ORDER_SHIPPING(ORD_ID)';
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_ORDER_SHIPPING_STORE ON BEX_ORDER_SHIPPING(STR_ID)';
  END IF;
END;
/

PROMPT Payment-pending order runtime structures are ready.
