WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET SERVEROUTPUT ON
SET DEFINE OFF

PROMPT Ensuring purchase delivery runtime structures...

DECLARE
  l_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO l_count
    FROM USER_TABLES WHERE TABLE_NAME='BEX_PURCHASE_DELIVERY';

  IF l_count=0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE BEX_PURCHASE_DELIVERY(
        PDL_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
        PDL_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
        PUR_ID NUMBER(19) NOT NULL,
        ADR_ID NUMBER(19) NOT NULL,
        PDL_LABEL VARCHAR2(100 CHAR),
        PDL_ZIP_CODE VARCHAR2(10 CHAR) NOT NULL,
        PDL_STREET VARCHAR2(200 CHAR) NOT NULL,
        PDL_NUMBER VARCHAR2(50 CHAR) NOT NULL,
        PDL_COMPLEMENT VARCHAR2(200 CHAR),
        PDL_DISTRICT VARCHAR2(100 CHAR) NOT NULL,
        PDL_CITY VARCHAR2(100 CHAR) NOT NULL,
        PDL_STATE CHAR(2 CHAR) NOT NULL,
        PDL_COUNTRY CHAR(2 CHAR) DEFAULT 'BR' NOT NULL,
        PDL_STATUS VARCHAR2(30 CHAR) DEFAULT 'ADDRESS_SELECTED' NOT NULL,
        PDL_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        PDL_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        PDL_CREATED_BY NUMBER,
        PDL_UPDATED_BY NUMBER,
        CONSTRAINT PK_PURCHASE_DELIVERY PRIMARY KEY(PDL_ID),
        CONSTRAINT UK_PURCHASE_DELIVERY_PUBLIC UNIQUE(PDL_PUBLIC_ID),
        CONSTRAINT UK_PURCHASE_DELIVERY_REQUEST UNIQUE(PUR_ID),
        CONSTRAINT FK_PDL_REQUEST FOREIGN KEY(PUR_ID)
          REFERENCES BEX_PURCHASE_REQUEST(PUR_ID),
        CONSTRAINT FK_PDL_ADDRESS FOREIGN KEY(ADR_ID)
          REFERENCES BEX_ADDRESS(ADR_ID),
        CONSTRAINT CK_PDL_STATUS CHECK(PDL_STATUS IN(
          'ADDRESS_SELECTED','SHIPPING_CALCULATED','CANCELLED'
        ))
      )
    ~';
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_PURCHASE_DELIVERY_ADDRESS '||
      'ON BEX_PURCHASE_DELIVERY(ADR_ID)';
  END IF;
END;
/

PROMPT Purchase delivery runtime structures are ready.
