WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET SERVEROUTPUT ON
SET DEFINE OFF

PROMPT Ensuring cart runtime structures...

DECLARE
  l_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO l_count FROM USER_TABLES WHERE TABLE_NAME='BEX_CART';
  IF l_count=0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE BEX_CART(
        CRT_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
        CRT_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
        PFL_ID NUMBER(19) NOT NULL,
        CRT_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
        CRT_EXPIRES_AT TIMESTAMP(6),
        CRT_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CRT_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CRT_CREATED_BY NUMBER,
        CRT_UPDATED_BY NUMBER,
        CONSTRAINT PK_CART PRIMARY KEY(CRT_ID),
        CONSTRAINT UK_CART_PUBLIC_ID UNIQUE(CRT_PUBLIC_ID),
        CONSTRAINT FK_CRT_PROFILE FOREIGN KEY(PFL_ID)
          REFERENCES BEX_PROFILE(PFL_ID),
        CONSTRAINT CK_CRT_STATUS CHECK(
          CRT_STATUS IN('ACTIVE','CHECKED_OUT','EXPIRED','ABANDONED')
        )
      )
    ~';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_CART_PROFILE ON BEX_CART(PFL_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_CART_STATUS ON BEX_CART(CRT_STATUS)';
    EXECUTE IMMEDIATE q'~
      CREATE UNIQUE INDEX UK_CART_ACTIVE_PROFILE ON BEX_CART(
        CASE WHEN CRT_STATUS='ACTIVE' THEN PFL_ID END
      )
    ~';
  END IF;

  SELECT COUNT(*) INTO l_count
    FROM USER_TABLES WHERE TABLE_NAME='BEX_CART_ITEM';
  IF l_count=0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE BEX_CART_ITEM(
        CTI_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
        CTI_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
        CRT_ID NUMBER(19) NOT NULL,
        PRD_ID NUMBER(19) NOT NULL,
        STR_ID NUMBER(19) NOT NULL,
        CTI_QUANTITY NUMBER(12) NOT NULL,
        CTI_UNIT_PRICE NUMBER(12,2) NOT NULL,
        CTI_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
        CTI_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CTI_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CTI_CREATED_BY NUMBER,
        CTI_UPDATED_BY NUMBER,
        CONSTRAINT PK_CART_ITEM PRIMARY KEY(CTI_ID),
        CONSTRAINT UK_CART_ITEM_PUBLIC_ID UNIQUE(CTI_PUBLIC_ID),
        CONSTRAINT FK_CTI_CART FOREIGN KEY(CRT_ID)
          REFERENCES BEX_CART(CRT_ID),
        CONSTRAINT FK_CTI_PRODUCT_STORE FOREIGN KEY(PRD_ID,STR_ID)
          REFERENCES BEX_PRODUCT(PRD_ID,STR_ID),
        CONSTRAINT CK_CTI_QUANTITY CHECK(CTI_QUANTITY>0),
        CONSTRAINT CK_CTI_PRICE CHECK(CTI_UNIT_PRICE>=0),
        CONSTRAINT CK_CTI_STATUS CHECK(CTI_STATUS IN('ACTIVE','REMOVED'))
      )
    ~';
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_CART_ITEM_CART ON BEX_CART_ITEM(CRT_ID)';
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_CART_ITEM_PRODUCT ON BEX_CART_ITEM(PRD_ID)';
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_CART_ITEM_STORE ON BEX_CART_ITEM(STR_ID)';
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_CART_ITEM_STATUS ON BEX_CART_ITEM(CTI_STATUS)';
    EXECUTE IMMEDIATE q'~
      CREATE UNIQUE INDEX UK_CART_ITEM_ACTIVE_PRODUCT ON BEX_CART_ITEM(
        CASE WHEN CTI_STATUS='ACTIVE' THEN CRT_ID END,
        CASE WHEN CTI_STATUS='ACTIVE' THEN PRD_ID END
      )
    ~';
  END IF;
END;
/

PROMPT Cart runtime structures are ready.
