SET SERVEROUTPUT ON SIZE UNLIMITED
SET DEFINE OFF
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT Installing verified Google profile name support...

@@packages/account/acc_social_auth_api_pkg.pks
SHOW ERRORS PACKAGE ACC_SOCIAL_AUTH_API_PKG
@@packages/account/acc_social_auth_api_pkg.pkb
SHOW ERRORS PACKAGE BODY ACC_SOCIAL_AUTH_API_PKG

DECLARE
  l_invalid_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*)
    INTO l_invalid_count
    FROM USER_OBJECTS
   WHERE OBJECT_NAME = 'ACC_SOCIAL_AUTH_API_PKG'
     AND OBJECT_TYPE IN ('PACKAGE', 'PACKAGE BODY')
     AND STATUS <> 'VALID';
  IF l_invalid_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20999, 'ACC_SOCIAL_AUTH_API_PKG remains invalid.');
  END IF;
  DBMS_OUTPUT.put_line('SUCCESS - VERIFIED GOOGLE PROFILE NAME INSTALLED');
END;
/

EXIT SUCCESS COMMIT
