WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET SERVEROUTPUT ON
SET DEFINE OFF

PROMPT Ensuring purchase shipping runtime structures...

DECLARE
  l_count PLS_INTEGER;
  PROCEDURE add_column(p_table VARCHAR2,p_column VARCHAR2,p_definition VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO l_count FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME=p_table AND COLUMN_NAME=p_column;
    IF l_count=0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE '||p_table||' ADD '||p_column||' '||p_definition;
    END IF;
  END;
BEGIN
  add_column('BEX_PURCHASE_DELIVERY','PDL_LATITUDE','NUMBER(10,7)');
  add_column('BEX_PURCHASE_DELIVERY','PDL_LONGITUDE','NUMBER(10,7)');

  SELECT COUNT(*) INTO l_count
  FROM USER_TABLES WHERE TABLE_NAME='BEX_STORE_SHIPPING_CONFIG';
  IF l_count=0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE BEX_STORE_SHIPPING_CONFIG(
        STR_ID NUMBER(19) NOT NULL,
        SSC_PICKUP_ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
        SSC_LOCAL_ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
        SSC_LOCAL_BASE_PRICE NUMBER(12,2) DEFAULT 7 NOT NULL,
        SSC_LOCAL_PRICE_PER_KM NUMBER(12,2) DEFAULT 1.8 NOT NULL,
        SSC_LOCAL_MAX_DISTANCE_KM NUMBER(10,2) DEFAULT 20 NOT NULL,
        SSC_PREPARATION_DAYS NUMBER(3) DEFAULT 1 NOT NULL,
        SSC_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        SSC_UPDATED_BY NUMBER,
        CONSTRAINT PK_STORE_SHIPPING_CONFIG PRIMARY KEY(STR_ID),
        CONSTRAINT FK_SSC_STORE FOREIGN KEY(STR_ID)
          REFERENCES BEX_STORE(STR_ID) ON DELETE CASCADE,
        CONSTRAINT CK_SSC_FLAGS CHECK(
          SSC_PICKUP_ENABLED IN(0,1) AND SSC_LOCAL_ENABLED IN(0,1)
        ),
        CONSTRAINT CK_SSC_VALUES CHECK(
          SSC_LOCAL_BASE_PRICE>=0 AND SSC_LOCAL_PRICE_PER_KM>=0
          AND SSC_LOCAL_MAX_DISTANCE_KM>0 AND SSC_PREPARATION_DAYS>=0
        )
      )
    ~';
  END IF;

  SELECT COUNT(*) INTO l_count
  FROM USER_TABLES WHERE TABLE_NAME='BEX_PURCHASE_SHIPPING_OPTION';
  IF l_count=0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE BEX_PURCHASE_SHIPPING_OPTION(
        PSO_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
        PSO_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
        PUR_ID NUMBER(19) NOT NULL,
        STR_ID NUMBER(19) NOT NULL,
        PSO_METHOD VARCHAR2(20 CHAR) NOT NULL,
        PSO_PRICE NUMBER(12,2) NOT NULL,
        PSO_DISTANCE_KM NUMBER(10,2),
        PSO_ESTIMATED_MIN_DAYS NUMBER(3) NOT NULL,
        PSO_ESTIMATED_MAX_DAYS NUMBER(3) NOT NULL,
        PSO_EXPIRES_AT TIMESTAMP(6) NOT NULL,
        PSO_IS_SELECTED NUMBER(1) DEFAULT 0 NOT NULL,
        PSO_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
        PSO_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        PSO_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        PSO_CREATED_BY NUMBER,
        PSO_UPDATED_BY NUMBER,
        CONSTRAINT PK_PURCHASE_SHIPPING_OPTION PRIMARY KEY(PSO_ID),
        CONSTRAINT UK_PSO_PUBLIC UNIQUE(PSO_PUBLIC_ID),
        CONSTRAINT UK_PSO_REQUEST_STORE_METHOD UNIQUE(PUR_ID,STR_ID,PSO_METHOD),
        CONSTRAINT FK_PSO_REQUEST FOREIGN KEY(PUR_ID)
          REFERENCES BEX_PURCHASE_REQUEST(PUR_ID),
        CONSTRAINT FK_PSO_STORE FOREIGN KEY(STR_ID)
          REFERENCES BEX_STORE(STR_ID),
        CONSTRAINT CK_PSO_METHOD CHECK(PSO_METHOD IN('PICKUP','LOCAL')),
        CONSTRAINT CK_PSO_PRICE CHECK(PSO_PRICE>=0),
        CONSTRAINT CK_PSO_DISTANCE CHECK(
          PSO_DISTANCE_KM IS NULL OR PSO_DISTANCE_KM>=0
        ),
        CONSTRAINT CK_PSO_DAYS CHECK(
          PSO_ESTIMATED_MIN_DAYS>=0
          AND PSO_ESTIMATED_MAX_DAYS>=PSO_ESTIMATED_MIN_DAYS
        ),
        CONSTRAINT CK_PSO_SELECTED CHECK(PSO_IS_SELECTED IN(0,1)),
        CONSTRAINT CK_PSO_STATUS CHECK(PSO_STATUS IN('ACTIVE','EXPIRED'))
      )
    ~';
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_PSO_REQUEST ON BEX_PURCHASE_SHIPPING_OPTION(PUR_ID)';
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_PSO_STORE ON BEX_PURCHASE_SHIPPING_OPTION(STR_ID)';
    EXECUTE IMMEDIATE q'~
      CREATE UNIQUE INDEX UK_PSO_SELECTED_STORE ON BEX_PURCHASE_SHIPPING_OPTION(
        CASE WHEN PSO_STATUS='ACTIVE' AND PSO_IS_SELECTED=1 THEN PUR_ID END,
        CASE WHEN PSO_STATUS='ACTIVE' AND PSO_IS_SELECTED=1 THEN STR_ID END
      )
    ~';
  END IF;
END;
/

PROMPT Purchase shipping runtime structures are ready.
