WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET SERVEROUTPUT ON
SET DEFINE OFF

PROMPT Ensuring purchase request runtime structures...

DECLARE
  l_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO l_count
    FROM USER_TABLES WHERE TABLE_NAME='BEX_PURCHASE_REQUEST';
  IF l_count=0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE BEX_PURCHASE_REQUEST(
        PUR_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
        PUR_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
        PFL_ID NUMBER(19) NOT NULL,
        PUR_STATUS VARCHAR2(30 CHAR) DEFAULT 'PENDING' NOT NULL,
        PUR_REQUESTED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        PUR_CONFIRMED_AT TIMESTAMP(6),
        PUR_RESPONSE_AT TIMESTAMP(6),
        PUR_EXPIRES_AT TIMESTAMP(6),
        PUR_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        PUR_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        PUR_CREATED_BY NUMBER,
        PUR_UPDATED_BY NUMBER,
        CONSTRAINT PK_PURCHASE_REQUEST PRIMARY KEY(PUR_ID),
        CONSTRAINT UK_PURCHASE_REQUEST_PUBLIC_ID UNIQUE(PUR_PUBLIC_ID),
        CONSTRAINT FK_PUR_PROFILE FOREIGN KEY(PFL_ID)
          REFERENCES BEX_PROFILE(PFL_ID),
        CONSTRAINT CK_PUR_STATUS CHECK(PUR_STATUS IN(
          'PENDING','PARTIALLY_APPROVED','APPROVED','REJECTED',
          'EXPIRED','CANCELLED'
        )),
        CONSTRAINT CK_PUR_TIMESTAMPS CHECK(
          (PUR_STATUS='APPROVED' AND PUR_RESPONSE_AT IS NOT NULL
            AND PUR_CONFIRMED_AT IS NOT NULL)
          OR(PUR_STATUS IN('PARTIALLY_APPROVED','REJECTED')
            AND PUR_RESPONSE_AT IS NOT NULL AND PUR_CONFIRMED_AT IS NULL)
          OR(PUR_STATUS IN('PENDING','EXPIRED','CANCELLED')
            AND PUR_CONFIRMED_AT IS NULL)
        )
      )
    ~';
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_PURCHASE_REQUEST_PROFILE '||
      'ON BEX_PURCHASE_REQUEST(PFL_ID)';
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_PURCHASE_REQUEST_STATUS '||
      'ON BEX_PURCHASE_REQUEST(PUR_STATUS)';
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_PURCHASE_REQUEST_REQUESTED_AT '||
      'ON BEX_PURCHASE_REQUEST(PUR_REQUESTED_AT)';
  END IF;

  SELECT COUNT(*) INTO l_count
    FROM USER_TABLES WHERE TABLE_NAME='BEX_PURCHASE_REQUEST_ITEM';
  IF l_count=0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE BEX_PURCHASE_REQUEST_ITEM(
        PRI_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
        PRI_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
        PUR_ID NUMBER(19) NOT NULL,
        PRD_ID NUMBER(19) NOT NULL,
        STR_ID NUMBER(19) NOT NULL,
        PRI_REQUESTED_QUANTITY NUMBER(12) NOT NULL,
        PRI_CONFIRMED_QUANTITY NUMBER(12),
        PRI_UNIT_PRICE NUMBER(12,2) NOT NULL,
        PRI_REJECT_REASON VARCHAR2(500 CHAR),
        PRI_STATUS VARCHAR2(30 CHAR) DEFAULT 'PENDING' NOT NULL,
        PRI_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        PRI_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        PRI_CREATED_BY NUMBER,
        PRI_UPDATED_BY NUMBER,
        CONSTRAINT PK_PURCHASE_REQUEST_ITEM PRIMARY KEY(PRI_ID),
        CONSTRAINT UK_PURCHASE_REQUEST_ITEM_PUBLIC_ID UNIQUE(PRI_PUBLIC_ID),
        CONSTRAINT FK_PRI_REQUEST FOREIGN KEY(PUR_ID)
          REFERENCES BEX_PURCHASE_REQUEST(PUR_ID),
        CONSTRAINT FK_PRI_PRODUCT_STORE FOREIGN KEY(PRD_ID,STR_ID)
          REFERENCES BEX_PRODUCT(PRD_ID,STR_ID),
        CONSTRAINT CK_PRI_REQUESTED_QTY CHECK(PRI_REQUESTED_QUANTITY>0),
        CONSTRAINT CK_PRI_CONFIRMED_QTY CHECK(
          PRI_CONFIRMED_QUANTITY IS NULL OR
          (PRI_CONFIRMED_QUANTITY>=0
            AND PRI_CONFIRMED_QUANTITY<=PRI_REQUESTED_QUANTITY)
        ),
        CONSTRAINT CK_PRI_PRICE CHECK(PRI_UNIT_PRICE>=0),
        CONSTRAINT CK_PRI_STATUS CHECK(PRI_STATUS IN(
          'PENDING','PARTIALLY_APPROVED','APPROVED','REJECTED'
        )),
        CONSTRAINT CK_PRI_STATE CHECK(
          (PRI_STATUS='PENDING' AND PRI_CONFIRMED_QUANTITY IS NULL
            AND PRI_REJECT_REASON IS NULL)
          OR(PRI_STATUS='APPROVED'
            AND PRI_CONFIRMED_QUANTITY=PRI_REQUESTED_QUANTITY
            AND PRI_REJECT_REASON IS NULL)
          OR(PRI_STATUS='PARTIALLY_APPROVED'
            AND PRI_CONFIRMED_QUANTITY>0
            AND PRI_CONFIRMED_QUANTITY<PRI_REQUESTED_QUANTITY
            AND PRI_REJECT_REASON IS NULL)
          OR(PRI_STATUS='REJECTED' AND NVL(PRI_CONFIRMED_QUANTITY,0)=0
            AND PRI_REJECT_REASON IS NOT NULL)
        )
      )
    ~';
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_PURCHASE_REQUEST_ITEM_REQUEST '||
      'ON BEX_PURCHASE_REQUEST_ITEM(PUR_ID)';
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_PURCHASE_REQUEST_ITEM_STORE '||
      'ON BEX_PURCHASE_REQUEST_ITEM(STR_ID)';
    EXECUTE IMMEDIATE
      'CREATE INDEX IDX_PURCHASE_REQUEST_ITEM_STATUS '||
      'ON BEX_PURCHASE_REQUEST_ITEM(PRI_STATUS)';
  END IF;
END;
/

PROMPT Purchase request runtime structures are ready.
