SET LINESIZE 240
SET PAGESIZE 100
COLUMN AEL_OCCURRED_AT FORMAT A26
COLUMN AEL_TRACE_ID FORMAT A32
COLUMN AEL_COMPONENT FORMAT A30
COLUMN AEL_OPERATION FORMAT A30
COLUMN AEL_SQL_MESSAGE FORMAT A80
COLUMN AEL_BACKTRACE FORMAT A100

SELECT AEL_ID,
       TO_CHAR(AEL_OCCURRED_AT, 'YYYY-MM-DD HH24:MI:SS.FF3') AEL_OCCURRED_AT,
       AEL_TRACE_ID,
       AEL_COMPONENT,
       AEL_OPERATION,
       AEL_ACTOR_ID,
       AEL_SQL_CODE,
       AEL_SQL_MESSAGE,
       AEL_BACKTRACE
  FROM BEX_API_ERROR_LOG
 ORDER BY AEL_ID DESC
 FETCH FIRST 20 ROWS ONLY;
