WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_SHIPMENT(
  SHP_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  SHP_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  ORD_ID NUMBER(19) NOT NULL,
  STR_ID NUMBER(19) NOT NULL,
  ADR_ID NUMBER(19) NOT NULL,
  DLP_ID NUMBER(19) NOT NULL,
  SHP_TRACKING_CODE VARCHAR2(100 CHAR),
  SHP_ESTIMATED_DELIVERY_AT TIMESTAMP(6),
  SHP_DELIVERED_AT TIMESTAMP(6),
  SHP_STATUS VARCHAR2(20 CHAR) DEFAULT 'CREATED' NOT NULL,
  SHP_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  SHP_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  SHP_CREATED_BY NUMBER,
  SHP_UPDATED_BY NUMBER,
  CONSTRAINT PK_SHIPMENT PRIMARY KEY(SHP_ID),
  CONSTRAINT UK_SHIPMENT_PUBLIC_ID UNIQUE(SHP_PUBLIC_ID),
  CONSTRAINT FK_SHP_ORDER FOREIGN KEY(ORD_ID) REFERENCES BEX_ORDER(ORD_ID),
  CONSTRAINT FK_SHP_STORE FOREIGN KEY(STR_ID) REFERENCES BEX_STORE(STR_ID),
  CONSTRAINT FK_SHP_ADDRESS FOREIGN KEY(ADR_ID) REFERENCES BEX_ADDRESS(ADR_ID),
  CONSTRAINT FK_SHP_DELIVERY_PROFILE FOREIGN KEY(DLP_ID) REFERENCES BEX_DELIVERY_PROFILE(DLP_ID),
  CONSTRAINT CK_SHP_STATUS CHECK(SHP_STATUS IN(
    'CREATED','READY','IN_TRANSIT','DELIVERED','CANCELLED')),
  CONSTRAINT CK_SHP_DELIVERED CHECK(
    (SHP_STATUS='DELIVERED' AND SHP_DELIVERED_AT IS NOT NULL) OR
    (SHP_STATUS<>'DELIVERED' AND SHP_DELIVERED_AT IS NULL))
);
CREATE INDEX IDX_SHIPMENT_ORDER ON BEX_SHIPMENT(ORD_ID);
CREATE INDEX IDX_SHIPMENT_STORE ON BEX_SHIPMENT(STR_ID);
CREATE INDEX IDX_SHIPMENT_ADDRESS ON BEX_SHIPMENT(ADR_ID);
CREATE INDEX IDX_SHIPMENT_DELIVERY_PROFILE ON BEX_SHIPMENT(DLP_ID);
CREATE INDEX IDX_SHIPMENT_STATUS ON BEX_SHIPMENT(SHP_STATUS);
COMMENT ON TABLE BEX_SHIPMENT IS 'Operational delivery for one store inside an order';
PROMPT BEX_SHIPMENT structure installed successfully.
