WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_SHIPMENT_ITEM(
  SHI_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  SHI_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  SHP_ID NUMBER(19) NOT NULL,
  ORI_ID NUMBER(19) NOT NULL,
  PRD_ID NUMBER(19) NOT NULL,
  SHI_QUANTITY NUMBER(12) NOT NULL,
  SHI_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  SHI_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  SHI_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  SHI_CREATED_BY NUMBER,
  SHI_UPDATED_BY NUMBER,
  CONSTRAINT PK_SHIPMENT_ITEM PRIMARY KEY(SHI_ID),
  CONSTRAINT UK_SHIPMENT_ITEM_PUBLIC_ID UNIQUE(SHI_PUBLIC_ID),
  CONSTRAINT FK_SHI_SHIPMENT FOREIGN KEY(SHP_ID) REFERENCES BEX_SHIPMENT(SHP_ID),
  CONSTRAINT FK_SHI_ORDER_ITEM FOREIGN KEY(ORI_ID) REFERENCES BEX_ORDER_ITEM(ORI_ID),
  CONSTRAINT FK_SHI_PRODUCT FOREIGN KEY(PRD_ID) REFERENCES BEX_PRODUCT(PRD_ID),
  CONSTRAINT CK_SHI_QUANTITY CHECK(SHI_QUANTITY>0),
  CONSTRAINT CK_SHI_STATUS CHECK(SHI_STATUS IN('ACTIVE','CANCELLED'))
);
CREATE INDEX IDX_SHIPMENT_ITEM_SHIPMENT ON BEX_SHIPMENT_ITEM(SHP_ID);
CREATE INDEX IDX_SHIPMENT_ITEM_ORDER_ITEM ON BEX_SHIPMENT_ITEM(ORI_ID);
CREATE INDEX IDX_SHIPMENT_ITEM_PRODUCT ON BEX_SHIPMENT_ITEM(PRD_ID);
CREATE INDEX IDX_SHIPMENT_ITEM_STATUS ON BEX_SHIPMENT_ITEM(SHI_STATUS);
CREATE UNIQUE INDEX UK_SHIPMENT_ITEM_ACTIVE_ORDER_ITEM ON BEX_SHIPMENT_ITEM(
  CASE WHEN SHI_STATUS='ACTIVE' THEN ORI_ID END);
COMMENT ON TABLE BEX_SHIPMENT_ITEM IS 'Order item allocated to an operational shipment';
PROMPT BEX_SHIPMENT_ITEM structure installed successfully.
