WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_DELIVERY_PROFILE(
  DLP_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  DLP_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  DLP_CODE VARCHAR2(50 CHAR) NOT NULL,
  DLP_NAME VARCHAR2(100 CHAR) NOT NULL,
  DLP_DESCRIPTION VARCHAR2(500 CHAR),
  DLP_BASE_PRICE NUMBER(12,2),
  DLP_MAX_DISTANCE_KM NUMBER(10,2),
  DLP_MAX_WEIGHT_KG NUMBER(10,2),
  DLP_IS_EXPRESS NUMBER(1) DEFAULT 0 NOT NULL,
  DLP_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  DLP_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  DLP_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  DLP_CREATED_BY NUMBER,
  DLP_UPDATED_BY NUMBER,
  CONSTRAINT PK_DELIVERY_PROFILE PRIMARY KEY(DLP_ID),
  CONSTRAINT UK_DELIVERY_PROFILE_PUBLIC_ID UNIQUE(DLP_PUBLIC_ID),
  CONSTRAINT UK_DELIVERY_PROFILE_CODE UNIQUE(DLP_CODE),
  CONSTRAINT CK_DLP_CODE CHECK(DLP_CODE IN('PICKUP','LOCAL','EXPRESS','NATIONAL')),
  CONSTRAINT CK_DLP_VALUES CHECK(
    (DLP_BASE_PRICE IS NULL OR DLP_BASE_PRICE>=0) AND
    (DLP_MAX_DISTANCE_KM IS NULL OR DLP_MAX_DISTANCE_KM>0) AND
    (DLP_MAX_WEIGHT_KG IS NULL OR DLP_MAX_WEIGHT_KG>0)),
  CONSTRAINT CK_DLP_EXPRESS CHECK(DLP_IS_EXPRESS IN(0,1)),
  CONSTRAINT CK_DLP_STATUS CHECK(DLP_STATUS IN('ACTIVE','INACTIVE'))
);
CREATE INDEX IDX_DELIVERY_PROFILE_STATUS ON BEX_DELIVERY_PROFILE(DLP_STATUS);
COMMENT ON TABLE BEX_DELIVERY_PROFILE IS 'Global delivery modality configuration';
PROMPT BEX_DELIVERY_PROFILE structure installed successfully.
