WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_ORDER(
  ORD_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  ORD_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  PUR_ID NUMBER(19) NOT NULL,
  PFL_ID NUMBER(19) NOT NULL,
  ORD_NUMBER VARCHAR2(50 CHAR) NOT NULL,
  ORD_SUBTOTAL_AMOUNT NUMBER(12,2) NOT NULL,
  ORD_DISCOUNT_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  ORD_SHIPPING_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  ORD_TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
  ORD_STATUS VARCHAR2(20 CHAR) DEFAULT 'PAID' NOT NULL,
  ORD_PAID_AT TIMESTAMP(6) NOT NULL,
  ORD_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  ORD_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  ORD_CREATED_BY NUMBER,
  ORD_UPDATED_BY NUMBER,
  CONSTRAINT PK_ORDER PRIMARY KEY(ORD_ID),
  CONSTRAINT UK_ORDER_PUBLIC_ID UNIQUE(ORD_PUBLIC_ID),
  CONSTRAINT UK_ORDER_NUMBER UNIQUE(ORD_NUMBER),
  CONSTRAINT UK_ORDER_REQUEST UNIQUE(PUR_ID),
  CONSTRAINT FK_ORD_REQUEST FOREIGN KEY(PUR_ID) REFERENCES BEX_PURCHASE_REQUEST(PUR_ID),
  CONSTRAINT FK_ORD_PROFILE FOREIGN KEY(PFL_ID) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT CK_ORD_AMOUNTS CHECK(
    ORD_SUBTOTAL_AMOUNT>=0 AND ORD_DISCOUNT_AMOUNT>=0 AND
    ORD_SHIPPING_AMOUNT>=0 AND
    ORD_TOTAL_AMOUNT=ORD_SUBTOTAL_AMOUNT-ORD_DISCOUNT_AMOUNT+ORD_SHIPPING_AMOUNT),
  CONSTRAINT CK_ORD_STATUS CHECK(ORD_STATUS IN(
    'PAID','PROCESSING','SHIPPED','COMPLETED','CANCELLED'))
);
CREATE INDEX IDX_ORDER_PROFILE ON BEX_ORDER(PFL_ID);
CREATE INDEX IDX_ORDER_STATUS ON BEX_ORDER(ORD_STATUS);
COMMENT ON TABLE BEX_ORDER IS 'Paid order created from a finalized purchase request';
PROMPT BEX_ORDER structure installed successfully.
