WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_CART(
  CRT_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  CRT_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  PFL_ID NUMBER(19) NOT NULL,
  CRT_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  CRT_EXPIRES_AT TIMESTAMP(6),
  CRT_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CRT_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CRT_CREATED_BY NUMBER,
  CRT_UPDATED_BY NUMBER,
  CONSTRAINT PK_CART PRIMARY KEY(CRT_ID),
  CONSTRAINT UK_CART_PUBLIC_ID UNIQUE(CRT_PUBLIC_ID),
  CONSTRAINT FK_CRT_PROFILE FOREIGN KEY(PFL_ID) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT CK_CRT_STATUS CHECK(CRT_STATUS IN(
    'ACTIVE','CHECKED_OUT','EXPIRED','ABANDONED'))
);
CREATE INDEX IDX_CART_PROFILE ON BEX_CART(PFL_ID);
CREATE INDEX IDX_CART_STATUS ON BEX_CART(CRT_STATUS);
CREATE UNIQUE INDEX UK_CART_ACTIVE_PROFILE ON BEX_CART(
  CASE WHEN CRT_STATUS='ACTIVE' THEN PFL_ID END);
COMMENT ON TABLE BEX_CART IS 'Temporary multi-store purchase intention';
COMMENT ON COLUMN BEX_CART.CRT_ID IS 'Internal Oracle identity';
COMMENT ON COLUMN BEX_CART.CRT_PUBLIC_ID IS 'Immutable public identifier';
COMMENT ON COLUMN BEX_CART.PFL_ID IS 'Profile that owns the cart';
COMMENT ON COLUMN BEX_CART.CRT_STATUS IS 'Cart lifecycle status';
COMMENT ON COLUMN BEX_CART.CRT_EXPIRES_AT IS 'Optional expiration timestamp';
COMMENT ON COLUMN BEX_CART.CRT_CREATED_AT IS 'Creation timestamp';
COMMENT ON COLUMN BEX_CART.CRT_UPDATED_AT IS 'Last update timestamp';
COMMENT ON COLUMN BEX_CART.CRT_CREATED_BY IS 'Optional creator technical actor';
COMMENT ON COLUMN BEX_CART.CRT_UPDATED_BY IS 'Optional updater technical actor';
PROMPT BEX_CART structure installed successfully.
