WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_PURCHASE_REQUEST(
  PUR_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  PUR_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  PFL_ID NUMBER(19) NOT NULL,
  PUR_STATUS VARCHAR2(30 CHAR) DEFAULT 'PENDING' NOT NULL,
  PUR_REQUESTED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PUR_CONFIRMED_AT TIMESTAMP(6),
  PUR_RESPONSE_AT TIMESTAMP(6),
  PUR_EXPIRES_AT TIMESTAMP(6),
  PUR_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PUR_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PUR_CREATED_BY NUMBER,
  PUR_UPDATED_BY NUMBER,
  CONSTRAINT PK_PURCHASE_REQUEST PRIMARY KEY(PUR_ID),
  CONSTRAINT UK_PURCHASE_REQUEST_PUBLIC_ID UNIQUE(PUR_PUBLIC_ID),
  CONSTRAINT FK_PUR_PROFILE FOREIGN KEY(PFL_ID) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT CK_PUR_STATUS CHECK(PUR_STATUS IN(
    'PENDING','PARTIALLY_APPROVED','APPROVED','REJECTED','EXPIRED','CANCELLED')),
  CONSTRAINT CK_PUR_TIMESTAMPS CHECK(
    (PUR_STATUS='APPROVED' AND PUR_RESPONSE_AT IS NOT NULL AND PUR_CONFIRMED_AT IS NOT NULL)
    OR(PUR_STATUS IN('PARTIALLY_APPROVED','REJECTED') AND PUR_RESPONSE_AT IS NOT NULL AND PUR_CONFIRMED_AT IS NULL)
    OR(PUR_STATUS IN('PENDING','EXPIRED','CANCELLED') AND PUR_CONFIRMED_AT IS NULL))
);
CREATE INDEX IDX_PURCHASE_REQUEST_PROFILE ON BEX_PURCHASE_REQUEST(PFL_ID);
CREATE INDEX IDX_PURCHASE_REQUEST_STATUS ON BEX_PURCHASE_REQUEST(PUR_STATUS);
CREATE INDEX IDX_PURCHASE_REQUEST_REQUESTED_AT ON BEX_PURCHASE_REQUEST(PUR_REQUESTED_AT);
COMMENT ON TABLE BEX_PURCHASE_REQUEST IS 'Multi-store commercial availability request';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST.PUR_ID IS 'Internal Oracle identity';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST.PUR_PUBLIC_ID IS 'Immutable public identifier';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST.PFL_ID IS 'Requesting profile';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST.PUR_STATUS IS 'Aggregated request status';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST.PUR_REQUESTED_AT IS 'Request timestamp';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST.PUR_CONFIRMED_AT IS 'Total approval timestamp';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST.PUR_RESPONSE_AT IS 'Commercial response timestamp';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST.PUR_EXPIRES_AT IS 'Optional expiration timestamp';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST.PUR_CREATED_AT IS 'Creation timestamp';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST.PUR_UPDATED_AT IS 'Last update timestamp';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST.PUR_CREATED_BY IS 'Optional creator technical actor';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST.PUR_UPDATED_BY IS 'Optional updater technical actor';
PROMPT BEX_PURCHASE_REQUEST structure installed successfully.
