WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_CART_ITEM(
  CTI_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  CTI_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  CRT_ID NUMBER(19) NOT NULL,
  PRD_ID NUMBER(19) NOT NULL,
  STR_ID NUMBER(19) NOT NULL,
  CTI_QUANTITY NUMBER(12) NOT NULL,
  CTI_UNIT_PRICE NUMBER(12,2) NOT NULL,
  CTI_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  CTI_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CTI_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CTI_CREATED_BY NUMBER,
  CTI_UPDATED_BY NUMBER,
  CONSTRAINT PK_CART_ITEM PRIMARY KEY(CTI_ID),
  CONSTRAINT UK_CART_ITEM_PUBLIC_ID UNIQUE(CTI_PUBLIC_ID),
  CONSTRAINT FK_CTI_CART FOREIGN KEY(CRT_ID) REFERENCES BEX_CART(CRT_ID),
  CONSTRAINT FK_CTI_PRODUCT_STORE FOREIGN KEY(PRD_ID,STR_ID)
    REFERENCES BEX_PRODUCT(PRD_ID,STR_ID),
  CONSTRAINT CK_CTI_QUANTITY CHECK(CTI_QUANTITY>0),
  CONSTRAINT CK_CTI_PRICE CHECK(CTI_UNIT_PRICE>=0),
  CONSTRAINT CK_CTI_STATUS CHECK(CTI_STATUS IN('ACTIVE','REMOVED'))
);
CREATE INDEX IDX_CART_ITEM_CART ON BEX_CART_ITEM(CRT_ID);
CREATE INDEX IDX_CART_ITEM_PRODUCT ON BEX_CART_ITEM(PRD_ID);
CREATE INDEX IDX_CART_ITEM_STORE ON BEX_CART_ITEM(STR_ID);
CREATE INDEX IDX_CART_ITEM_STATUS ON BEX_CART_ITEM(CTI_STATUS);
CREATE UNIQUE INDEX UK_CART_ITEM_ACTIVE_PRODUCT ON BEX_CART_ITEM(
  CASE WHEN CTI_STATUS='ACTIVE' THEN CRT_ID END,
  CASE WHEN CTI_STATUS='ACTIVE' THEN PRD_ID END);
COMMENT ON TABLE BEX_CART_ITEM IS 'Product selection without stock reservation';
COMMENT ON COLUMN BEX_CART_ITEM.CTI_ID IS 'Internal Oracle identity';
COMMENT ON COLUMN BEX_CART_ITEM.CTI_PUBLIC_ID IS 'Immutable public identifier';
COMMENT ON COLUMN BEX_CART_ITEM.CRT_ID IS 'Owning cart';
COMMENT ON COLUMN BEX_CART_ITEM.PRD_ID IS 'Selected product';
COMMENT ON COLUMN BEX_CART_ITEM.STR_ID IS 'Product store preserved by composite FK';
COMMENT ON COLUMN BEX_CART_ITEM.CTI_QUANTITY IS 'Positive selected quantity';
COMMENT ON COLUMN BEX_CART_ITEM.CTI_UNIT_PRICE IS 'Estimated unit price snapshot';
COMMENT ON COLUMN BEX_CART_ITEM.CTI_STATUS IS 'Logical item status';
COMMENT ON COLUMN BEX_CART_ITEM.CTI_CREATED_AT IS 'Creation timestamp';
COMMENT ON COLUMN BEX_CART_ITEM.CTI_UPDATED_AT IS 'Last update timestamp';
COMMENT ON COLUMN BEX_CART_ITEM.CTI_CREATED_BY IS 'Optional creator technical actor';
COMMENT ON COLUMN BEX_CART_ITEM.CTI_UPDATED_BY IS 'Optional updater technical actor';
PROMPT BEX_CART_ITEM structure installed successfully.
