WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_PURCHASE_REQUEST_ITEM(
  PRI_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  PRI_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  PUR_ID NUMBER(19) NOT NULL,
  PRD_ID NUMBER(19) NOT NULL,
  STR_ID NUMBER(19) NOT NULL,
  PRI_REQUESTED_QUANTITY NUMBER(12) NOT NULL,
  PRI_CONFIRMED_QUANTITY NUMBER(12),
  PRI_UNIT_PRICE NUMBER(12,2) NOT NULL,
  PRI_REJECT_REASON VARCHAR2(500 CHAR),
  PRI_STATUS VARCHAR2(30 CHAR) DEFAULT 'PENDING' NOT NULL,
  PRI_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PRI_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PRI_CREATED_BY NUMBER,
  PRI_UPDATED_BY NUMBER,
  CONSTRAINT PK_PURCHASE_REQUEST_ITEM PRIMARY KEY(PRI_ID),
  CONSTRAINT UK_PURCHASE_REQUEST_ITEM_PUBLIC_ID UNIQUE(PRI_PUBLIC_ID),
  CONSTRAINT FK_PRI_REQUEST FOREIGN KEY(PUR_ID) REFERENCES BEX_PURCHASE_REQUEST(PUR_ID),
  CONSTRAINT FK_PRI_PRODUCT_STORE FOREIGN KEY(PRD_ID,STR_ID)
    REFERENCES BEX_PRODUCT(PRD_ID,STR_ID),
  CONSTRAINT CK_PRI_REQUESTED_QTY CHECK(PRI_REQUESTED_QUANTITY>0),
  CONSTRAINT CK_PRI_CONFIRMED_QTY CHECK(PRI_CONFIRMED_QUANTITY IS NULL OR(
    PRI_CONFIRMED_QUANTITY>=0 AND PRI_CONFIRMED_QUANTITY<=PRI_REQUESTED_QUANTITY)),
  CONSTRAINT CK_PRI_PRICE CHECK(PRI_UNIT_PRICE>=0),
  CONSTRAINT CK_PRI_STATUS CHECK(PRI_STATUS IN(
    'PENDING','PARTIALLY_APPROVED','APPROVED','REJECTED')),
  CONSTRAINT CK_PRI_STATE CHECK(
    (PRI_STATUS='PENDING' AND PRI_CONFIRMED_QUANTITY IS NULL AND PRI_REJECT_REASON IS NULL)
    OR(PRI_STATUS='APPROVED' AND PRI_CONFIRMED_QUANTITY=PRI_REQUESTED_QUANTITY AND PRI_REJECT_REASON IS NULL)
    OR(PRI_STATUS='PARTIALLY_APPROVED' AND PRI_CONFIRMED_QUANTITY>0
      AND PRI_CONFIRMED_QUANTITY<PRI_REQUESTED_QUANTITY AND PRI_REJECT_REASON IS NULL)
    OR(PRI_STATUS='REJECTED' AND NVL(PRI_CONFIRMED_QUANTITY,0)=0 AND PRI_REJECT_REASON IS NOT NULL))
);
CREATE INDEX IDX_PURCHASE_REQUEST_ITEM_REQUEST ON BEX_PURCHASE_REQUEST_ITEM(PUR_ID);
CREATE INDEX IDX_PURCHASE_REQUEST_ITEM_PRODUCT ON BEX_PURCHASE_REQUEST_ITEM(PRD_ID);
CREATE INDEX IDX_PURCHASE_REQUEST_ITEM_STORE ON BEX_PURCHASE_REQUEST_ITEM(STR_ID);
CREATE INDEX IDX_PURCHASE_REQUEST_ITEM_STATUS ON BEX_PURCHASE_REQUEST_ITEM(PRI_STATUS);
COMMENT ON TABLE BEX_PURCHASE_REQUEST_ITEM IS 'Requested product and commercial response snapshot';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST_ITEM.PRI_ID IS 'Internal Oracle identity';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST_ITEM.PRI_PUBLIC_ID IS 'Immutable public identifier';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST_ITEM.PUR_ID IS 'Owning purchase request';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST_ITEM.PRD_ID IS 'Requested product';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST_ITEM.STR_ID IS 'Responsible product store';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST_ITEM.PRI_REQUESTED_QUANTITY IS 'Positive requested quantity';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST_ITEM.PRI_CONFIRMED_QUANTITY IS 'Optional confirmed quantity';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST_ITEM.PRI_UNIT_PRICE IS 'Unit price snapshot at checkout';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST_ITEM.PRI_REJECT_REASON IS 'Required individual rejection reason';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST_ITEM.PRI_STATUS IS 'Item response status';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST_ITEM.PRI_CREATED_AT IS 'Creation timestamp';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST_ITEM.PRI_UPDATED_AT IS 'Last update timestamp';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST_ITEM.PRI_CREATED_BY IS 'Optional creator technical actor';
COMMENT ON COLUMN BEX_PURCHASE_REQUEST_ITEM.PRI_UPDATED_BY IS 'Optional updater technical actor';
PROMPT BEX_PURCHASE_REQUEST_ITEM structure installed successfully.
