WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_ORDER_ITEM(
  ORI_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  ORI_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  ORD_ID NUMBER(19) NOT NULL,
  PRD_ID NUMBER(19) NOT NULL,
  STR_ID NUMBER(19) NOT NULL,
  ORI_QUANTITY NUMBER(12) NOT NULL,
  ORI_UNIT_PRICE NUMBER(12,2) NOT NULL,
  ORI_DISCOUNT_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  ORI_TOTAL_PRICE NUMBER(12,2) NOT NULL,
  ORI_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  ORI_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  ORI_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  ORI_CREATED_BY NUMBER,
  ORI_UPDATED_BY NUMBER,
  CONSTRAINT PK_ORDER_ITEM PRIMARY KEY(ORI_ID),
  CONSTRAINT UK_ORDER_ITEM_PUBLIC_ID UNIQUE(ORI_PUBLIC_ID),
  CONSTRAINT FK_ORI_ORDER FOREIGN KEY(ORD_ID) REFERENCES BEX_ORDER(ORD_ID),
  CONSTRAINT FK_ORI_PRODUCT_STORE FOREIGN KEY(PRD_ID,STR_ID)
    REFERENCES BEX_PRODUCT(PRD_ID,STR_ID),
  CONSTRAINT CK_ORI_QUANTITY CHECK(ORI_QUANTITY>0),
  CONSTRAINT CK_ORI_AMOUNTS CHECK(
    ORI_UNIT_PRICE>=0 AND ORI_DISCOUNT_AMOUNT>=0 AND
    ORI_TOTAL_PRICE=ORI_QUANTITY*ORI_UNIT_PRICE-ORI_DISCOUNT_AMOUNT AND
    ORI_TOTAL_PRICE>=0),
  CONSTRAINT CK_ORI_STATUS CHECK(ORI_STATUS IN('ACTIVE','CANCELLED'))
);
CREATE INDEX IDX_ORDER_ITEM_ORDER ON BEX_ORDER_ITEM(ORD_ID);
CREATE INDEX IDX_ORDER_ITEM_PRODUCT ON BEX_ORDER_ITEM(PRD_ID);
CREATE INDEX IDX_ORDER_ITEM_STORE ON BEX_ORDER_ITEM(STR_ID);
CREATE INDEX IDX_ORDER_ITEM_STATUS ON BEX_ORDER_ITEM(ORI_STATUS);
COMMENT ON TABLE BEX_ORDER_ITEM IS 'Immutable commercial item snapshot of an order';
PROMPT BEX_ORDER_ITEM structure installed successfully.
