WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_STORE_FOLLOWER(
  STF_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,STF_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  STR_ID NUMBER(19) NOT NULL,PFL_ID NUMBER(19) NOT NULL,STF_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  STF_FOLLOWED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,STF_UNFOLLOWED_AT TIMESTAMP(6),
  STF_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,STF_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  STF_CREATED_BY NUMBER(19),STF_UPDATED_BY NUMBER(19),
  CONSTRAINT PK_STORE_FOLLOWER PRIMARY KEY(STF_ID),CONSTRAINT UK_STORE_FOLLOWER_PUBLIC_ID UNIQUE(STF_PUBLIC_ID),
  CONSTRAINT FK_STF_STORE FOREIGN KEY(STR_ID)REFERENCES BEX_STORE(STR_ID),
  CONSTRAINT FK_STF_PROFILE FOREIGN KEY(PFL_ID)REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT FK_STF_CREATED_BY FOREIGN KEY(STF_CREATED_BY)REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT FK_STF_UPDATED_BY FOREIGN KEY(STF_UPDATED_BY)REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT CK_STF_STATUS CHECK(STF_STATUS IN('ACTIVE','INACTIVE')),
  CONSTRAINT CK_STF_STATE CHECK((STF_STATUS='ACTIVE' AND STF_UNFOLLOWED_AT IS NULL)OR(STF_STATUS='INACTIVE' AND STF_UNFOLLOWED_AT IS NOT NULL))
);
CREATE UNIQUE INDEX UK_STF_STORE_PROFILE_ACTIVE ON BEX_STORE_FOLLOWER(
  CASE WHEN STF_STATUS='ACTIVE' THEN STR_ID END,CASE WHEN STF_STATUS='ACTIVE' THEN PFL_ID END);
CREATE INDEX IDX_STORE_FOLLOWER_STORE ON BEX_STORE_FOLLOWER(STR_ID);
CREATE INDEX IDX_STORE_FOLLOWER_PROFILE ON BEX_STORE_FOLLOWER(PFL_ID);
CREATE INDEX IDX_STORE_FOLLOWER_STATUS ON BEX_STORE_FOLLOWER(STF_STATUS);
PROMPT BEX_STORE_FOLLOWER structure installed successfully.
