WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_BUSINESS_CONFIGURATION(
  BCF_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,BCF_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  BCF_CODE VARCHAR2(100 CHAR) NOT NULL,BCF_MODULE VARCHAR2(50 CHAR) NOT NULL,BCF_NAME VARCHAR2(150 CHAR) NOT NULL,
  BCF_DESCRIPTION VARCHAR2(1000 CHAR),BCF_VALUE_TEXT VARCHAR2(4000 CHAR),BCF_VALUE_NUMBER NUMBER(19,6),
  BCF_VALUE_BOOLEAN CHAR(1 CHAR),BCF_UNIT VARCHAR2(50 CHAR),BCF_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  BCF_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,BCF_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  BCF_CREATED_BY NUMBER(19),BCF_UPDATED_BY NUMBER(19),
  CONSTRAINT PK_BUSINESS_CONFIGURATION PRIMARY KEY(BCF_ID),
  CONSTRAINT UK_BUSINESS_CONFIGURATION_PUBLIC_ID UNIQUE(BCF_PUBLIC_ID),
  CONSTRAINT UK_BUSINESS_CONFIGURATION_CODE UNIQUE(BCF_CODE),
  CONSTRAINT FK_BCF_CREATED_BY FOREIGN KEY(BCF_CREATED_BY) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT FK_BCF_UPDATED_BY FOREIGN KEY(BCF_UPDATED_BY) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT CK_BCF_BOOLEAN CHECK(BCF_VALUE_BOOLEAN IS NULL OR BCF_VALUE_BOOLEAN IN('Y','N')),
  CONSTRAINT CK_BCF_STATUS CHECK(BCF_STATUS IN('ACTIVE','INACTIVE')),
  CONSTRAINT CK_BCF_VALUE CHECK(
    (BCF_VALUE_TEXT IS NOT NULL AND BCF_VALUE_NUMBER IS NULL AND BCF_VALUE_BOOLEAN IS NULL) OR
    (BCF_VALUE_TEXT IS NULL AND BCF_VALUE_NUMBER IS NOT NULL AND BCF_VALUE_BOOLEAN IS NULL) OR
    (BCF_VALUE_TEXT IS NULL AND BCF_VALUE_NUMBER IS NULL AND BCF_VALUE_BOOLEAN IS NOT NULL)
  )
);
CREATE INDEX IDX_BUSINESS_CONFIGURATION_MODULE ON BEX_BUSINESS_CONFIGURATION(BCF_MODULE);
CREATE INDEX IDX_BUSINESS_CONFIGURATION_STATUS ON BEX_BUSINESS_CONFIGURATION(BCF_STATUS);
MERGE INTO BEX_BUSINESS_CONFIGURATION d USING(
  SELECT 'PURCHASE_STORE_CONFIRMATION_TIMEOUT' code,'PURCHASE' module,'Tempo de confirmação do Brechó' name,NULL txt,24 num,NULL bool,'hours' unit FROM dual UNION ALL
  SELECT 'PURCHASE_PAYMENT_TIMEOUT','PURCHASE','Tempo de pagamento',NULL,30,NULL,'minutes' FROM dual UNION ALL
  SELECT 'FUNDS_RETENTION_DAYS','FINANCE','Retenção de fundos',NULL,7,NULL,'days' FROM dual UNION ALL
  SELECT 'PAYOUT_MINIMUM_AMOUNT','FINANCE','Valor mínimo para payout',NULL,50,NULL,'reais' FROM dual UNION ALL
  SELECT 'PAYOUT_PROCESSING_TIME','FINANCE','Tempo de processamento do payout',NULL,3,NULL,'business_days' FROM dual UNION ALL
  SELECT 'DELIVERY_OWN_RADIUS','LOGISTICS','Raio de entrega própria',NULL,10,NULL,'km' FROM dual UNION ALL
  SELECT 'DELIVERY_AUTO_CARRIER','LOGISTICS','Uso automático de carrier',NULL,NULL,'Y',NULL FROM dual UNION ALL
  SELECT 'CATALOG_PUBLIC_QUESTIONS','CATALOG','Perguntas públicas',NULL,NULL,'Y',NULL FROM dual UNION ALL
  SELECT 'CATALOG_MIN_IMAGES','CATALOG','Mínimo de imagens',NULL,1,NULL,NULL FROM dual UNION ALL
  SELECT 'CATALOG_MAX_IMAGES','CATALOG','Máximo de imagens',NULL,8,NULL,NULL FROM dual UNION ALL
  SELECT 'RETURN_FIRST_FREE','POST_SALE','Primeira devolução gratuita',NULL,NULL,'Y',NULL FROM dual UNION ALL
  SELECT 'RETURN_ALLOW_PARTIAL','POST_SALE','Devolução parcial',NULL,NULL,'Y',NULL FROM dual UNION ALL
  SELECT 'RETURN_REQUIRE_PHOTO','POST_SALE','Exigir foto',NULL,NULL,'Y',NULL FROM dual UNION ALL
  SELECT 'LOYALTY_PURCHASE_ENABLED','LOYALTY','Fidelidade por compra',NULL,NULL,'N',NULL FROM dual UNION ALL
  SELECT 'LOYALTY_REVIEW_ENABLED','LOYALTY','Fidelidade por avaliação',NULL,NULL,'N',NULL FROM dual UNION ALL
  SELECT 'LOYALTY_PHOTO_ENABLED','LOYALTY','Fidelidade por foto',NULL,NULL,'N',NULL FROM dual UNION ALL
  SELECT 'SOCIAL_PUBLIC_COMMENTS','SOCIAL','Comentários públicos',NULL,NULL,'Y',NULL FROM dual UNION ALL
  SELECT 'SOCIAL_MODERATION_REQUIRED','SOCIAL','Moderação obrigatória',NULL,NULL,'Y',NULL FROM dual
)s ON(d.BCF_CODE=s.code)WHEN NOT MATCHED THEN INSERT(
  BCF_PUBLIC_ID,BCF_CODE,BCF_MODULE,BCF_NAME,BCF_VALUE_TEXT,BCF_VALUE_NUMBER,BCF_VALUE_BOOLEAN,BCF_UNIT
) VALUES(LOWER(RAWTOHEX(SYS_GUID())),s.code,s.module,s.name,s.txt,s.num,s.bool,s.unit);
PROMPT BEX_BUSINESS_CONFIGURATION structure installed successfully.
