WHENEVER SQLERROR EXIT SQL.SQLCODE
@@install_acc_service_pkg.sql
@@acc_auth_api_pkg.pks
@@acc_auth_api_pkg.pkb
DECLARE n NUMBER;BEGIN SELECT COUNT(*) INTO n FROM USER_OBJECTS WHERE OBJECT_NAME='ACC_AUTH_API_PKG' AND OBJECT_TYPE IN('PACKAGE','PACKAGE BODY') AND STATUS='VALID';IF n<>2 THEN RAISE_APPLICATION_ERROR(-20999,'ACC_AUTH_API_PKG invalido.');END IF;END;
/
PROMPT ACCOUNT AUTH module installed successfully.
