WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_ROLE(
  ROL_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,ROL_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  ROL_CODE VARCHAR2(50 CHAR) NOT NULL,ROL_NAME VARCHAR2(100 CHAR) NOT NULL,ROL_DESCRIPTION VARCHAR2(500 CHAR),
  ROL_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,ROL_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  ROL_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,ROL_CREATED_BY NUMBER(19),ROL_UPDATED_BY NUMBER(19),
  CONSTRAINT PK_ROLE PRIMARY KEY(ROL_ID),CONSTRAINT UK_ROLE_PUBLIC_ID UNIQUE(ROL_PUBLIC_ID),
  CONSTRAINT UK_ROLE_CODE UNIQUE(ROL_CODE),CONSTRAINT FK_ROL_CREATED_BY FOREIGN KEY(ROL_CREATED_BY)REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT FK_ROL_UPDATED_BY FOREIGN KEY(ROL_UPDATED_BY)REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT CK_ROL_CODE CHECK(ROL_CODE IN('SYSTEM','ADMIN','CUSTOMER','STORE_OWNER','STORE_ATTENDANT')),
  CONSTRAINT CK_ROL_STATUS CHECK(ROL_STATUS IN('ACTIVE','INACTIVE'))
);
CREATE INDEX IDX_ROLE_STATUS ON BEX_ROLE(ROL_STATUS);
MERGE INTO BEX_ROLE d USING(
  SELECT 'SYSTEM' code,'System' name FROM dual UNION ALL SELECT 'ADMIN','Administrator' FROM dual
  UNION ALL SELECT 'CUSTOMER','Customer' FROM dual UNION ALL SELECT 'STORE_OWNER','Store Owner' FROM dual
  UNION ALL SELECT 'STORE_ATTENDANT','Store Attendant' FROM dual
)s ON(d.ROL_CODE=s.code)WHEN NOT MATCHED THEN INSERT(ROL_PUBLIC_ID,ROL_CODE,ROL_NAME)
VALUES(LOWER(RAWTOHEX(SYS_GUID())),s.code,s.name);
PROMPT BEX_ROLE structure installed successfully.
