WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_PROFILE_ROLE(
  PRL_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,PRL_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  PFL_ID NUMBER(19) NOT NULL,ROL_ID NUMBER(19) NOT NULL,PRL_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  PRL_GRANTED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,PRL_EXPIRES_AT TIMESTAMP(6),
  PRL_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,PRL_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PRL_CREATED_BY NUMBER(19),PRL_UPDATED_BY NUMBER(19),
  CONSTRAINT PK_PROFILE_ROLE PRIMARY KEY(PRL_ID),CONSTRAINT UK_PROFILE_ROLE_PUBLIC_ID UNIQUE(PRL_PUBLIC_ID),
  CONSTRAINT UK_PROFILE_ROLE_PROFILE_ROLE UNIQUE(PFL_ID,ROL_ID),
  CONSTRAINT FK_PRL_PROFILE FOREIGN KEY(PFL_ID)REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT FK_PRL_ROLE FOREIGN KEY(ROL_ID)REFERENCES BEX_ROLE(ROL_ID),
  CONSTRAINT FK_PRL_CREATED_BY FOREIGN KEY(PRL_CREATED_BY)REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT FK_PRL_UPDATED_BY FOREIGN KEY(PRL_UPDATED_BY)REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT CK_PRL_STATUS CHECK(PRL_STATUS IN('ACTIVE','INACTIVE')),
  CONSTRAINT CK_PRL_EXPIRY CHECK(PRL_EXPIRES_AT IS NULL OR PRL_EXPIRES_AT>PRL_GRANTED_AT)
);
CREATE INDEX IDX_PROFILE_ROLE_STATUS ON BEX_PROFILE_ROLE(PRL_STATUS);
PROMPT BEX_PROFILE_ROLE structure installed successfully.
