WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_ADDRESS(
  ADR_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  ADR_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  PFL_ID NUMBER(19) NOT NULL,
  ADR_LABEL VARCHAR2(100 CHAR),
  ADR_ZIP_CODE VARCHAR2(10 CHAR) NOT NULL,
  ADR_STREET VARCHAR2(200 CHAR) NOT NULL,
  ADR_NUMBER VARCHAR2(50 CHAR) NOT NULL,
  ADR_COMPLEMENT VARCHAR2(200 CHAR),
  ADR_DISTRICT VARCHAR2(100 CHAR) NOT NULL,
  ADR_CITY VARCHAR2(100 CHAR) NOT NULL,
  ADR_STATE CHAR(2 CHAR) NOT NULL,
  ADR_COUNTRY CHAR(2 CHAR) DEFAULT 'BR' NOT NULL,
  ADR_LATITUDE NUMBER(10,7),
  ADR_LONGITUDE NUMBER(10,7),
  ADR_IS_DEFAULT NUMBER(1) DEFAULT 0 NOT NULL,
  ADR_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  ADR_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  ADR_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  ADR_CREATED_BY NUMBER,
  ADR_UPDATED_BY NUMBER,
  CONSTRAINT PK_ADDRESS PRIMARY KEY(ADR_ID),
  CONSTRAINT UK_ADDRESS_PUBLIC_ID UNIQUE(ADR_PUBLIC_ID),
  CONSTRAINT FK_ADR_PROFILE FOREIGN KEY(PFL_ID) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT CK_ADR_DEFAULT CHECK(ADR_IS_DEFAULT IN(0,1)),
  CONSTRAINT CK_ADR_STATUS CHECK(ADR_STATUS IN('ACTIVE','INACTIVE')),
  CONSTRAINT CK_ADR_GEO CHECK(
    (ADR_LATITUDE IS NULL AND ADR_LONGITUDE IS NULL) OR
    (ADR_LATITUDE BETWEEN -90 AND 90 AND ADR_LONGITUDE BETWEEN -180 AND 180))
);
CREATE INDEX IDX_ADDRESS_PROFILE ON BEX_ADDRESS(PFL_ID);
CREATE INDEX IDX_ADDRESS_STATUS ON BEX_ADDRESS(ADR_STATUS);
CREATE INDEX IDX_ADDRESS_ZIP_CODE ON BEX_ADDRESS(ADR_ZIP_CODE);
CREATE UNIQUE INDEX UK_ADDRESS_DEFAULT_ACTIVE ON BEX_ADDRESS(
  CASE WHEN ADR_STATUS='ACTIVE' AND ADR_IS_DEFAULT=1 THEN PFL_ID END);
COMMENT ON TABLE BEX_ADDRESS IS 'Profile delivery or operational address';
PROMPT BEX_ADDRESS structure installed successfully.
