WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE ON
DEFINE BEX_TABLE_ROOT = '&1'
@&BEX_TABLE_ROOT/identity/bex_role.sql
@&BEX_TABLE_ROOT/identity/bex_profile_role.sql
UNDEFINE BEX_TABLE_ROOT
SET DEFINE OFF
PROMPT IDENTITY AUTHORIZATION structures installed successfully.
