WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE ON
DEFINE BEX_TABLE_ROOT = '&1'
@&BEX_TABLE_ROOT/configuration/bex_business_configuration.sql
UNDEFINE BEX_TABLE_ROOT
SET DEFINE OFF
PROMPT BUSINESS CONFIGURATION structures installed successfully.
