SET SERVEROUTPUT ON
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE
DECLARE
  l_count PLS_INTEGER; l_account NUMBER; l_store NUMBER;
  l_category NUMBER; l_product NUMBER; l_raised BOOLEAN;
  l_token VARCHAR2(12):=LOWER(SUBSTR(RAWTOHEX(SYS_GUID()),1,12));
  PROCEDURE fail(p VARCHAR2) IS BEGIN RAISE_APPLICATION_ERROR(-20999,p); END;
  PROCEDURE ok(p BOOLEAN,m VARCHAR2) IS BEGIN IF p IS NULL OR NOT p THEN fail(m); END IF; END;
BEGIN
  SELECT COUNT(*) INTO l_count FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME='BEX_PRODUCT_IMAGE';
  ok(l_count=12,'PRODUCT_IMAGE deve possuir 12 colunas.');
  SELECT COUNT(*) INTO l_count FROM USER_CONSTRAINTS
   WHERE TABLE_NAME='BEX_PRODUCT_IMAGE' AND STATUS='ENABLED'
     AND CONSTRAINT_NAME IN (
       'PK_PRODUCT_IMAGE','UK_PRODUCT_IMAGE_PUBLIC_ID','FK_PIM_PRODUCT',
       'CK_PIM_SORT_ORDER','CK_PIM_IS_PRIMARY','CK_PIM_STATUS'
     );
  ok(l_count=6,'Constraints divergentes.');
  SELECT COUNT(*) INTO l_count FROM USER_COL_COMMENTS
   WHERE TABLE_NAME='BEX_PRODUCT_IMAGE' AND COMMENTS IS NOT NULL;
  ok(l_count=12,'Comentarios divergentes.');
  INSERT INTO BEX_ACCOUNT(
    ACC_PUBLIC_ID,ACC_EMAIL,ACC_PASSWORD_HASH,ACC_PASSWORD_CHANGED_AT,ACC_STATUS
  ) VALUES(
    LOWER(RAWTOHEX(SYS_GUID())),'pim.'||l_token||'@example.invalid',
    'test-hash',SYSTIMESTAMP,'ACTIVE'
  ) RETURNING ACC_ID INTO l_account;
  INSERT INTO BEX_STORE(STR_PUBLIC_ID,ACC_ID,STR_NAME,STR_SLUG)
  VALUES(LOWER(RAWTOHEX(SYS_GUID())),l_account,'PIM Store','pim-'||l_token)
  RETURNING STR_ID INTO l_store;
  INSERT INTO BEX_CATEGORY(CAT_PUBLIC_ID,CAT_NAME,CAT_SLUG)
  VALUES(LOWER(RAWTOHEX(SYS_GUID())),'PIM Category','pim-cat-'||l_token)
  RETURNING CAT_ID INTO l_category;
  INSERT INTO BEX_PRODUCT(
    PRD_PUBLIC_ID,STR_ID,CAT_ID,PRD_TITLE,PRD_SLUG,
    PRD_PRICE,PRD_QUANTITY,PRD_CONDITION
  ) VALUES(
    LOWER(RAWTOHEX(SYS_GUID())),l_store,l_category,'PIM Product',
    'pim-product-'||l_token,10,1,'GOOD'
  ) RETURNING PRD_ID INTO l_product;
  INSERT INTO BEX_PRODUCT_IMAGE(
    PIM_PUBLIC_ID,PRD_ID,PIM_URL,PIM_SORT_ORDER,PIM_IS_PRIMARY
  ) VALUES(LOWER(RAWTOHEX(SYS_GUID())),l_product,'https://img.invalid/a.jpg',0,1);
  l_raised:=FALSE;
  BEGIN
    INSERT INTO BEX_PRODUCT_IMAGE(
      PIM_PUBLIC_ID,PRD_ID,PIM_URL,PIM_SORT_ORDER,PIM_IS_PRIMARY
    ) VALUES(LOWER(RAWTOHEX(SYS_GUID())),l_product,'https://img.invalid/b.jpg',1,1);
  EXCEPTION WHEN DUP_VAL_ON_INDEX THEN l_raised:=TRUE; END;
  ok(l_raised,'Produto aceitou duas imagens principais ativas.');
  INSERT INTO BEX_PRODUCT_IMAGE(
    PIM_PUBLIC_ID,PRD_ID,PIM_URL,PIM_SORT_ORDER,PIM_IS_PRIMARY,PIM_STATUS
  ) VALUES(
    LOWER(RAWTOHEX(SYS_GUID())),l_product,'https://img.invalid/c.jpg',2,1,'INACTIVE'
  );
  DBMS_OUTPUT.PUT_LINE('BEX_PRODUCT_IMAGE physical contract: PASSED');
  ROLLBACK;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/
