SET SERVEROUTPUT ON
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE
DECLARE
  l_count PLS_INTEGER; l_account NUMBER; l_product NUMBER;
  l_store NUMBER; l_profile NUMBER; l_category NUMBER;
  l_other_store NUMBER; l_raised BOOLEAN;
  l_token VARCHAR2(12):=LOWER(SUBSTR(RAWTOHEX(SYS_GUID()),1,12));
  PROCEDURE fail(p VARCHAR2) IS BEGIN RAISE_APPLICATION_ERROR(-20999,p); END;
  PROCEDURE ok(p BOOLEAN,m VARCHAR2) IS BEGIN IF p IS NULL OR NOT p THEN fail(m); END IF; END;
BEGIN
  SELECT COUNT(*) INTO l_count FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME='BEX_PRODUCT_QUESTION';
  ok(l_count=15,'PRODUCT_QUESTION deve possuir 15 colunas.');
  SELECT COUNT(*) INTO l_count FROM USER_CONSTRAINTS
   WHERE TABLE_NAME='BEX_PRODUCT_QUESTION' AND STATUS='ENABLED'
     AND CONSTRAINT_NAME IN (
       'PK_PRODUCT_QUESTION','UK_PRODUCT_QUESTION_PUBLIC_ID',
       'FK_PQA_PRODUCT_STORE','FK_PQA_QUESTION_BY','FK_PQA_ANSWERED_BY',
       'CK_PQA_STATUS','CK_PQA_ANSWER_STATE'
     );
  ok(l_count=7,'Constraints divergentes.');
  SELECT COUNT(*) INTO l_count FROM USER_COL_COMMENTS
   WHERE TABLE_NAME='BEX_PRODUCT_QUESTION' AND COMMENTS IS NOT NULL;
  ok(l_count=15,'Comentarios divergentes.');
  INSERT INTO BEX_ACCOUNT(
    ACC_PUBLIC_ID,ACC_EMAIL,ACC_PASSWORD_HASH,ACC_PASSWORD_CHANGED_AT,ACC_STATUS
  ) VALUES(
    LOWER(RAWTOHEX(SYS_GUID())),'pqa.'||l_token||'@example.invalid',
    'test-hash',SYSTIMESTAMP,'ACTIVE'
  ) RETURNING ACC_ID INTO l_account;
  INSERT INTO BEX_PROFILE(ACC_ID,PFL_PUBLIC_ID,PFL_DISPLAY_NAME)
  VALUES(l_account,LOWER(RAWTOHEX(SYS_GUID())),'Question Profile')
  RETURNING PFL_ID INTO l_profile;
  INSERT INTO BEX_STORE(STR_PUBLIC_ID,ACC_ID,STR_NAME,STR_SLUG)
  VALUES(LOWER(RAWTOHEX(SYS_GUID())),l_account,'PQA Store','pqa-'||l_token)
  RETURNING STR_ID INTO l_store;
  INSERT INTO BEX_STORE(STR_PUBLIC_ID,ACC_ID,STR_NAME,STR_SLUG)
  VALUES(
    LOWER(RAWTOHEX(SYS_GUID())),l_account,'Other PQA Store',
    'other-pqa-'||l_token
  ) RETURNING STR_ID INTO l_other_store;
  INSERT INTO BEX_CATEGORY(CAT_PUBLIC_ID,CAT_NAME,CAT_SLUG)
  VALUES(LOWER(RAWTOHEX(SYS_GUID())),'PQA Category','pqa-cat-'||l_token)
  RETURNING CAT_ID INTO l_category;
  INSERT INTO BEX_PRODUCT(
    PRD_PUBLIC_ID,STR_ID,CAT_ID,PRD_TITLE,PRD_SLUG,
    PRD_PRICE,PRD_QUANTITY,PRD_CONDITION
  ) VALUES(
    LOWER(RAWTOHEX(SYS_GUID())),l_store,l_category,'PQA Product',
    'pqa-product-'||l_token,10,1,'GOOD'
  ) RETURNING PRD_ID INTO l_product;
  INSERT INTO BEX_PRODUCT_QUESTION(
    PQA_PUBLIC_ID,PRD_ID,STR_ID,PFL_QUESTION_BY,PQA_QUESTION_TEXT
  ) VALUES(
    LOWER(RAWTOHEX(SYS_GUID())),l_product,l_store,l_profile,'Ainda disponivel?'
  );
  l_raised:=FALSE;
  BEGIN
    INSERT INTO BEX_PRODUCT_QUESTION(
      PQA_PUBLIC_ID,PRD_ID,STR_ID,PFL_QUESTION_BY,PQA_QUESTION_TEXT
    ) VALUES(
      LOWER(RAWTOHEX(SYS_GUID())),l_product,l_other_store,l_profile,'Loja errada'
    );
  EXCEPTION WHEN OTHERS THEN l_raised:=SQLCODE=-2291; END;
  ok(l_raised,'STORE divergente foi aceita.');
  l_raised:=FALSE;
  BEGIN
    INSERT INTO BEX_PRODUCT_QUESTION(
      PQA_PUBLIC_ID,PRD_ID,STR_ID,PFL_QUESTION_BY,PQA_QUESTION_TEXT,
      PQA_ANSWER_TEXT
    ) VALUES(
      LOWER(RAWTOHEX(SYS_GUID())),l_product,l_store,l_profile,'Pergunta','Resposta'
    );
  EXCEPTION WHEN OTHERS THEN l_raised:=SQLCODE=-2290; END;
  ok(l_raised,'Resposta parcial foi aceita.');
  DBMS_OUTPUT.PUT_LINE('BEX_PRODUCT_QUESTION physical contract: PASSED');
  ROLLBACK;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/
