CREATE TABLE BEX_NOTIFICATION_DELIVERY(
  NDL_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  NTF_ID NUMBER(19) NOT NULL,
  NDL_CHANNEL VARCHAR2(20 CHAR) NOT NULL,
  NDL_STATUS VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
  NDL_ATTEMPTS NUMBER(5) DEFAULT 0 NOT NULL,
  NDL_SENT_AT TIMESTAMP(6),
  CONSTRAINT PK_NOTIFICATION_DELIVERY PRIMARY KEY(NDL_ID),
  CONSTRAINT FK_NDL_NOTIFICATION FOREIGN KEY(NTF_ID) REFERENCES BEX_NOTIFICATION(NTF_ID),
  CONSTRAINT UK_NDL_CHANNEL UNIQUE(NTF_ID,NDL_CHANNEL),
  CONSTRAINT CK_NDL_CHANNEL CHECK(NDL_CHANNEL IN('IN_APP','EMAIL','PUSH')),
  CONSTRAINT CK_NDL_STATUS CHECK(NDL_STATUS IN('PENDING','SENT','FAILED'))
);
CREATE INDEX IDX_NDL_NOTIFICATION ON BEX_NOTIFICATION_DELIVERY(NTF_ID,NDL_STATUS);
PROMPT BEX_NOTIFICATION_DELIVERY structure installed successfully.
