WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_NOTIFICATION(
  NTF_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  NTF_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  PFL_ID NUMBER(19) NOT NULL,
  NTF_TYPE VARCHAR2(80 CHAR) NOT NULL,
  NTF_TITLE VARCHAR2(200 CHAR) NOT NULL,
  NTF_BODY VARCHAR2(2000 CHAR) NOT NULL,
  NTF_STATUS VARCHAR2(20 CHAR) DEFAULT 'UNREAD' NOT NULL,
  NTF_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  NTF_READ_AT TIMESTAMP(6),
  CONSTRAINT PK_NOTIFICATION PRIMARY KEY(NTF_ID),
  CONSTRAINT UK_NOTIFICATION_PUBLIC_ID UNIQUE(NTF_PUBLIC_ID),
  CONSTRAINT FK_NOTIFICATION_PROFILE FOREIGN KEY(PFL_ID) REFERENCES BEX_PROFILE(PFL_ID),
  CONSTRAINT CK_NOTIFICATION_STATUS CHECK(NTF_STATUS IN('UNREAD','READ','ARCHIVED'))
);
CREATE INDEX IDX_NOTIFICATION_PROFILE ON BEX_NOTIFICATION(PFL_ID,NTF_STATUS,NTF_CREATED_AT);
PROMPT BEX_NOTIFICATION structure installed successfully.
