CREATE TABLE BEX_NOTIFICATION_TEMPLATE(
  NTP_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  NTP_CODE VARCHAR2(100 CHAR) NOT NULL,
  NTP_CHANNEL VARCHAR2(20 CHAR) NOT NULL,
  NTP_TITLE VARCHAR2(200 CHAR) NOT NULL,
  NTP_BODY VARCHAR2(4000 CHAR) NOT NULL,
  NTP_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT PK_NOTIFICATION_TEMPLATE PRIMARY KEY(NTP_ID),
  CONSTRAINT UK_NTP_CODE_CHANNEL UNIQUE(NTP_CODE,NTP_CHANNEL),
  CONSTRAINT CK_NTP_CHANNEL CHECK(NTP_CHANNEL IN('IN_APP','EMAIL','PUSH')),
  CONSTRAINT CK_NTP_STATUS CHECK(NTP_STATUS IN('ACTIVE','INACTIVE'))
);
PROMPT BEX_NOTIFICATION_TEMPLATE structure installed successfully.
