WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_PAYMENT_PROVIDER(
  PPR_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  PPR_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  PPR_CODE VARCHAR2(50 CHAR) NOT NULL,
  PPR_NAME VARCHAR2(100 CHAR) NOT NULL,
  PPR_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  PPR_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PPR_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PPR_CREATED_BY NUMBER,PPR_UPDATED_BY NUMBER,
  CONSTRAINT PK_PAYMENT_PROVIDER PRIMARY KEY(PPR_ID),
  CONSTRAINT UK_PAYMENT_PROVIDER_PUBLIC_ID UNIQUE(PPR_PUBLIC_ID),
  CONSTRAINT UK_PAYMENT_PROVIDER_CODE UNIQUE(PPR_CODE),
  CONSTRAINT CK_PPR_STATUS CHECK(PPR_STATUS IN('ACTIVE','INACTIVE'))
);
CREATE INDEX IDX_PAYMENT_PROVIDER_STATUS ON BEX_PAYMENT_PROVIDER(PPR_STATUS);
COMMENT ON TABLE BEX_PAYMENT_PROVIDER IS 'Configured external payment gateway without credentials';
PROMPT BEX_PAYMENT_PROVIDER structure installed successfully.
