WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_PAYMENT_EVENT(
  PEV_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  PEV_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  PAY_ID NUMBER(19) NOT NULL,
  PEV_EVENT_TYPE VARCHAR2(50 CHAR) NOT NULL,
  PEV_EXTERNAL_EVENT_ID VARCHAR2(100 CHAR) NOT NULL,
  PEV_EVENT_AT TIMESTAMP(6) NOT NULL,
  PEV_RAW_PAYLOAD CLOB NOT NULL,
  PEV_STATUS VARCHAR2(20 CHAR) DEFAULT 'RECEIVED' NOT NULL,
  PEV_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PEV_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PEV_CREATED_BY NUMBER,PEV_UPDATED_BY NUMBER,
  CONSTRAINT PK_PAYMENT_EVENT PRIMARY KEY(PEV_ID),
  CONSTRAINT UK_PAYMENT_EVENT_PUBLIC_ID UNIQUE(PEV_PUBLIC_ID),
  CONSTRAINT UK_PAYMENT_EVENT_EXTERNAL UNIQUE(PAY_ID,PEV_EXTERNAL_EVENT_ID),
  CONSTRAINT FK_PEV_PAYMENT FOREIGN KEY(PAY_ID) REFERENCES BEX_PAYMENT(PAY_ID),
  CONSTRAINT CK_PEV_TYPE CHECK(PEV_EVENT_TYPE IN(
    'PAYMENT_APPROVED','PAYMENT_REJECTED','PAYMENT_CANCELLED','PAYMENT_REFUNDED')),
  CONSTRAINT CK_PEV_STATUS CHECK(PEV_STATUS IN('RECEIVED','PROCESSED','IGNORED','FAILED')),
  CONSTRAINT CK_PEV_PAYLOAD CHECK(PEV_RAW_PAYLOAD IS JSON)
);
CREATE INDEX IDX_PAYMENT_EVENT_PAYMENT ON BEX_PAYMENT_EVENT(PAY_ID);
CREATE INDEX IDX_PAYMENT_EVENT_STATUS ON BEX_PAYMENT_EVENT(PEV_STATUS);
CREATE INDEX IDX_PAYMENT_EVENT_EVENT_AT ON BEX_PAYMENT_EVENT(PEV_EVENT_AT);
COMMENT ON TABLE BEX_PAYMENT_EVENT IS 'Immutable idempotent gateway event and raw JSON evidence';
PROMPT BEX_PAYMENT_EVENT structure installed successfully.
