WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_PAYMENT(
  PAY_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  PAY_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  PUR_ID NUMBER(19) NOT NULL,
  ORD_ID NUMBER(19),
  PPR_ID NUMBER(19) NOT NULL,
  PAY_EXTERNAL_ID VARCHAR2(100 CHAR),
  PAY_AMOUNT NUMBER(12,2) NOT NULL,
  PAY_METHOD VARCHAR2(20 CHAR) NOT NULL,
  PAY_STATUS VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
  PAY_APPROVED_AT TIMESTAMP(6),
  PAY_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PAY_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  PAY_CREATED_BY NUMBER,PAY_UPDATED_BY NUMBER,
  CONSTRAINT PK_PAYMENT PRIMARY KEY(PAY_ID),
  CONSTRAINT UK_PAYMENT_PUBLIC_ID UNIQUE(PAY_PUBLIC_ID),
  CONSTRAINT UK_PAYMENT_REQUEST UNIQUE(PUR_ID),
  CONSTRAINT UK_PAYMENT_ORDER UNIQUE(ORD_ID),
  CONSTRAINT UK_PAYMENT_PROVIDER_EXTERNAL UNIQUE(PPR_ID,PAY_EXTERNAL_ID),
  CONSTRAINT FK_PAY_REQUEST FOREIGN KEY(PUR_ID) REFERENCES BEX_PURCHASE_REQUEST(PUR_ID),
  CONSTRAINT FK_PAY_ORDER FOREIGN KEY(ORD_ID) REFERENCES BEX_ORDER(ORD_ID),
  CONSTRAINT FK_PAY_PROVIDER FOREIGN KEY(PPR_ID) REFERENCES BEX_PAYMENT_PROVIDER(PPR_ID),
  CONSTRAINT CK_PAY_AMOUNT CHECK(PAY_AMOUNT>0),
  CONSTRAINT CK_PAY_METHOD CHECK(PAY_METHOD IN('PIX','CREDIT_CARD','DEBIT_CARD')),
  CONSTRAINT CK_PAY_STATUS CHECK(PAY_STATUS IN('PENDING','APPROVED','REJECTED','CANCELLED','REFUNDED')),
  CONSTRAINT CK_PAY_APPROVAL CHECK(
    (PAY_STATUS='APPROVED' AND ORD_ID IS NOT NULL AND PAY_APPROVED_AT IS NOT NULL) OR
    (PAY_STATUS<>'APPROVED' AND PAY_APPROVED_AT IS NULL))
);
CREATE INDEX IDX_PAYMENT_PROVIDER ON BEX_PAYMENT(PPR_ID);
CREATE INDEX IDX_PAYMENT_STATUS ON BEX_PAYMENT(PAY_STATUS);
COMMENT ON TABLE BEX_PAYMENT IS 'Payment attempt created before and linked to order after approval';
PROMPT BEX_PAYMENT structure installed successfully.
