WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_PAYOUT(
  POT_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  POT_PUBLIC_ID CHAR(32 CHAR) NOT NULL,STR_ID NUMBER(19) NOT NULL,
  POT_AMOUNT NUMBER(12,2) NOT NULL,POT_PIX_KEY VARCHAR2(200 CHAR) NOT NULL,
  POT_PIX_KEY_TYPE VARCHAR2(20 CHAR) NOT NULL,
  POT_REQUESTED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  POT_APPROVED_AT TIMESTAMP(6),POT_PAID_AT TIMESTAMP(6),POT_REJECTED_AT TIMESTAMP(6),
  POT_REJECT_REASON VARCHAR2(1000 CHAR),POT_STATUS VARCHAR2(20 CHAR) DEFAULT 'REQUESTED' NOT NULL,
  POT_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  POT_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  POT_CREATED_BY NUMBER,POT_UPDATED_BY NUMBER,
  CONSTRAINT PK_PAYOUT PRIMARY KEY(POT_ID),CONSTRAINT UK_PAYOUT_PUBLIC_ID UNIQUE(POT_PUBLIC_ID),
  CONSTRAINT FK_POT_STORE FOREIGN KEY(STR_ID) REFERENCES BEX_STORE(STR_ID),
  CONSTRAINT CK_POT_AMOUNT CHECK(POT_AMOUNT>0),
  CONSTRAINT CK_POT_PIX_TYPE CHECK(POT_PIX_KEY_TYPE IN('CPF','CNPJ','EMAIL','PHONE','RANDOM')),
  CONSTRAINT CK_POT_STATUS CHECK(POT_STATUS IN('REQUESTED','APPROVED','PAID','REJECTED')),
  CONSTRAINT CK_POT_STATE CHECK(
    (POT_STATUS='REQUESTED' AND POT_APPROVED_AT IS NULL AND POT_PAID_AT IS NULL AND POT_REJECTED_AT IS NULL)
    OR(POT_STATUS='APPROVED' AND POT_APPROVED_AT IS NOT NULL AND POT_PAID_AT IS NULL AND POT_REJECTED_AT IS NULL)
    OR(POT_STATUS='PAID' AND POT_APPROVED_AT IS NOT NULL AND POT_PAID_AT IS NOT NULL AND POT_REJECTED_AT IS NULL)
    OR(POT_STATUS='REJECTED' AND POT_PAID_AT IS NULL AND POT_REJECTED_AT IS NOT NULL AND POT_REJECT_REASON IS NOT NULL))
);
CREATE INDEX IDX_PAYOUT_STORE ON BEX_PAYOUT(STR_ID);
CREATE INDEX IDX_PAYOUT_STATUS ON BEX_PAYOUT(POT_STATUS);
CREATE INDEX IDX_PAYOUT_REQUESTED_AT ON BEX_PAYOUT(POT_REQUESTED_AT);
PROMPT BEX_PAYOUT structure installed successfully.
