WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_COMMISSION(
  COM_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  COM_PUBLIC_ID CHAR(32 CHAR) NOT NULL,
  STR_ID NUMBER(19) NOT NULL,ORD_ID NUMBER(19) NOT NULL,PAY_ID NUMBER(19) NOT NULL,
  COM_BASE_AMOUNT NUMBER(12,2) NOT NULL,
  COM_COMMISSION_RATE NUMBER(5,2) NOT NULL,
  COM_COMMISSION_AMOUNT NUMBER(12,2) NOT NULL,
  COM_GATEWAY_FEE_AMOUNT NUMBER(12,2) NOT NULL,
  COM_NET_AMOUNT NUMBER(12,2) NOT NULL,
  COM_STATUS VARCHAR2(20 CHAR) DEFAULT 'SETTLED' NOT NULL,
  COM_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  COM_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  COM_CREATED_BY NUMBER,COM_UPDATED_BY NUMBER,
  CONSTRAINT PK_COMMISSION PRIMARY KEY(COM_ID),
  CONSTRAINT UK_COMMISSION_PUBLIC_ID UNIQUE(COM_PUBLIC_ID),
  CONSTRAINT UK_COMMISSION_STORE_ORDER UNIQUE(STR_ID,ORD_ID),
  CONSTRAINT FK_COM_STORE FOREIGN KEY(STR_ID) REFERENCES BEX_STORE(STR_ID),
  CONSTRAINT FK_COM_ORDER FOREIGN KEY(ORD_ID) REFERENCES BEX_ORDER(ORD_ID),
  CONSTRAINT FK_COM_PAYMENT FOREIGN KEY(PAY_ID) REFERENCES BEX_PAYMENT(PAY_ID),
  CONSTRAINT CK_COM_VALUES CHECK(COM_BASE_AMOUNT>0 AND COM_COMMISSION_RATE BETWEEN 0 AND 100
    AND COM_COMMISSION_AMOUNT>=0 AND COM_GATEWAY_FEE_AMOUNT>=0 AND COM_NET_AMOUNT>=0
    AND COM_NET_AMOUNT=COM_BASE_AMOUNT-COM_COMMISSION_AMOUNT-COM_GATEWAY_FEE_AMOUNT),
  CONSTRAINT CK_COM_STATUS CHECK(COM_STATUS IN('SETTLED','REVERSED'))
);
CREATE INDEX IDX_COMMISSION_ORDER ON BEX_COMMISSION(ORD_ID);
CREATE INDEX IDX_COMMISSION_PAYMENT ON BEX_COMMISSION(PAY_ID);
CREATE INDEX IDX_COMMISSION_STATUS ON BEX_COMMISSION(COM_STATUS);
PROMPT BEX_COMMISSION structure installed successfully.
