WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE BEX_STORE_BALANCE_TRANSACTION(
  SBT_ID NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  SBT_PUBLIC_ID CHAR(32 CHAR) NOT NULL,STR_ID NUMBER(19) NOT NULL,
  ORD_ID NUMBER(19),PAY_ID NUMBER(19),POT_ID NUMBER(19),
  SBT_TYPE VARCHAR2(50 CHAR) NOT NULL,SBT_AMOUNT NUMBER(12,2) NOT NULL,
  SBT_DIRECTION VARCHAR2(10 CHAR) NOT NULL,SBT_AVAILABLE_AT TIMESTAMP(6),
  SBT_DESCRIPTION VARCHAR2(1000 CHAR),SBT_STATUS VARCHAR2(20 CHAR) DEFAULT 'POSTED' NOT NULL,
  SBT_CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  SBT_UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  SBT_CREATED_BY NUMBER,SBT_UPDATED_BY NUMBER,
  CONSTRAINT PK_STORE_BALANCE_TRANSACTION PRIMARY KEY(SBT_ID),
  CONSTRAINT UK_STORE_BALANCE_TRANSACTION_PUBLIC_ID UNIQUE(SBT_PUBLIC_ID),
  CONSTRAINT FK_SBT_STORE FOREIGN KEY(STR_ID) REFERENCES BEX_STORE(STR_ID),
  CONSTRAINT FK_SBT_ORDER FOREIGN KEY(ORD_ID) REFERENCES BEX_ORDER(ORD_ID),
  CONSTRAINT FK_SBT_PAYMENT FOREIGN KEY(PAY_ID) REFERENCES BEX_PAYMENT(PAY_ID),
  CONSTRAINT FK_SBT_PAYOUT FOREIGN KEY(POT_ID) REFERENCES BEX_PAYOUT(POT_ID),
  CONSTRAINT CK_SBT_TYPE CHECK(SBT_TYPE IN(
    'SALE_HOLD','HOLD_RELEASE','PAYOUT_RESERVE','PAYOUT_RESTORE','PAYOUT_PAID')),
  CONSTRAINT CK_SBT_AMOUNT CHECK(SBT_AMOUNT>0),
  CONSTRAINT CK_SBT_DIRECTION CHECK(SBT_DIRECTION IN('CREDIT','DEBIT')),
  CONSTRAINT CK_SBT_STATUS CHECK(SBT_STATUS='POSTED')
);
CREATE INDEX IDX_SBT_STORE ON BEX_STORE_BALANCE_TRANSACTION(STR_ID);
CREATE INDEX IDX_SBT_ORDER ON BEX_STORE_BALANCE_TRANSACTION(ORD_ID);
CREATE INDEX IDX_SBT_PAYMENT ON BEX_STORE_BALANCE_TRANSACTION(PAY_ID);
CREATE INDEX IDX_SBT_PAYOUT ON BEX_STORE_BALANCE_TRANSACTION(POT_ID);
CREATE INDEX IDX_SBT_CREATED_AT ON BEX_STORE_BALANCE_TRANSACTION(SBT_CREATED_AT);
PROMPT BEX_STORE_BALANCE_TRANSACTION structure installed successfully.
